export type Skill =
  | "Sensory Play"
  | "Motor Skills"
  | "Communication"
  | "Social Skills"
  | "Cognitive"
  | "Self-Care";

export const SKILLS: Skill[] = [
  "Sensory Play",
  "Motor Skills",
  "Communication",
  "Social Skills",
  "Cognitive",
  "Self-Care",
];

export type Energy = "low" | "low-med" | "med" | "med-high" | "high";

export type Hazard =
  | "choking"
  | "water"
  | "scissors"
  | "pressure"
  | "latex"
  | "allergen-scent"
  | "small-parts"
  | "food-dye"
  | "tape-skin"
  | "loud-sound";

export type Supervision = "spot" | "arm-reach" | "adult-led-prep";

export type Activity = {
  id: string;
  title: string;
  description: string;
  minAge: number;
  maxAge: number;
  minMinutes: number;
  maxMinutes: number;
  skill: Skill;
  materials: string[];
  steps: string[];
  secondarySkills?: Skill[];
  energy?: Energy;
  hazards?: Hazard[];
  supervision?: Supervision;
  regulation?: boolean;
  prepByAdult?: boolean;
  competitive?: boolean;
};

/** Broken/legacy favourite IDs that should resolve to a live catalog activity. */
export const ORPHAN_ACTIVITY_REDIRECTS: Record<string, string> = {
  "playdough-letters": "playdough-pinch",
};

export function canonicalActivityId(id: string): string {
  return ORPHAN_ACTIVITY_REDIRECTS[id] ?? id;
}

export const ACTIVITIES: Activity[] = [
  {
    id: "sensory-rice-bin",
    title: "Sensory Rice Bin",
    description:
      "A calming sensory bin with coloured rice for exploring textures (adult prepares the rice).",
    minAge: 2,
    maxAge: 3,
    minMinutes: 15,
    maxMinutes: 30,
    skill: "Sensory Play",
    secondarySkills: ["Motor Skills"],
    materials: ["Dry rice", "Food colouring (adult use)", "Shallow bin", "Scoops & cups"],
    steps: [
      "Adult: dye rice with a few drops of food colouring and let it dry fully.",
      "Pour into a shallow bin; add scoops and cups. Stay within arm's reach.",
      "Sit alongside your child, narrate textures, and redirect if rice goes toward the mouth.",
    ],
    energy: "low-med",
    hazards: ["choking", "food-dye"],
    supervision: "arm-reach",
    regulation: false,
    prepByAdult: true,
    competitive: false,
  },
  {
    id: "tape-rescue",
    title: "Tape Rescue",
    description: "Fine motor activity peeling tape off toys.",
    minAge: 2,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    secondarySkills: ["Cognitive"],
    materials: ["Masking tape", "Favourite small toys"],
    steps: [
      "Tape a few toys down to a table or tray (avoid wrapping tape around skin).",
      "Invite your child to free the toys by peeling the tape.",
      "Celebrate each rescue with a high five.",
    ],
    energy: "med",
    hazards: ["tape-skin"],
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "mirror-emotions",
    title: "Mirror Emotions",
    description: "Practise noticing and copying facial expressions together in a mirror.",
    minAge: 3,
    maxAge: 5,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Social Skills",
    secondarySkills: ["Communication"],
    materials: ["A mirror"],
    steps: [
      "Sit together in front of a mirror.",
      "Make a face and name the feeling out loud.",
      "Take turns copying each other's expressions.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "deep-pressure-sandwich",
    title: "Deep Pressure Sandwich",
    description:
      "Gentle cushion 'sandwich' play for calming body pressure — stop any time your child wants.",
    minAge: 2,
    maxAge: 8,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Sensory Play",
    secondarySkills: ["Self-Care"],
    materials: ["Two large cushions"],
    steps: [
      "Ask if they want to lie between two cushions (never force).",
      "Press gently and evenly on the cushions only — not on head, neck, or face. Check in constantly.",
      "Stop the moment they ask or look uncomfortable, and count the squeezes together.",
    ],
    energy: "low",
    hazards: ["pressure"],
    supervision: "arm-reach",
    regulation: true,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "story-time-props",
    title: "Story Time with Props",
    description: "Using objects to bring a story to life.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Communication",
    secondarySkills: ["Cognitive"],
    materials: ["Picture book", "Matching toys or household items"],
    steps: [
      "Pick a short familiar story.",
      "Hand your child a prop for each character.",
      "Pause and let them fill in the next line.",
    ],
    energy: "low-med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "rhyming-match",
    title: "Rhyming Match",
    description:
      "Play a simple rhyming game with picture pairs — listen for words that sound alike at the end.",
    minAge: 4,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Communication",
    secondarySkills: ["Cognitive"],
    materials: ["Picture cards or drawings"],
    steps: [
      "Lay out six picture cards in three rhyming pairs.",
      "Say each word slowly and stretch the ending sound.",
      "Let your child pair the ones that sound the same.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "puppet-conversation",
    title: "Puppet Conversation",
    description: "Encouraging verbal interaction through a proxy.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Communication",
    secondarySkills: ["Social Skills"],
    materials: ["Sock puppet or soft toy"],
    steps: [
      "Introduce the puppet with a silly voice.",
      "Have the puppet ask simple questions.",
      "Let your child answer the puppet, not you.",
    ],
    energy: "low-med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "interactive-bubble-chase",
    title: "Interactive Bubble Chase",
    description: "Joint attention and turn-taking fun.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Social Skills",
    secondarySkills: ["Motor Skills", "Sensory Play"],
    materials: ["Bubble mix", "Wand"],
    steps: [
      "Blow a few bubbles and wait for shared attention (eye contact is optional).",
      "Pause until your child signals for more.",
      "Swap roles and let them try blowing. Wipe slippery spots on the floor as you go.",
    ],
    energy: "med-high",
    hazards: ["water"],
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "shadow-puppets",
    title: "Shadow Puppets",
    description: "Exploring light and shadow to build imagination.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    secondarySkills: ["Communication"],
    materials: ["Torch", "Blank wall"],
    steps: [
      "Dim the room and shine a torch at the wall (never into eyes).",
      "Make animal shapes and guess each other's shadow.",
      "Invent a short story with two shadow characters.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "zip-loc-bag-painting",
    title: "Zip-Loc Bag Painting",
    description: "Mess-light sensory painting inside a sealed bag (adult seals and checks first).",
    minAge: 2,
    maxAge: 3,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Sensory Play",
    secondarySkills: ["Motor Skills"],
    materials: ["Zip-loc bag", "Two paint colours", "Tape"],
    steps: [
      "Adult: squirt paint into the bag, squeeze out air, seal tightly, and tape the seal.",
      "Tape the bag to a window or table so it cannot be peeled open easily.",
      "Let your child squish and swirl the colours; stop if the bag leaks.",
    ],
    energy: "low",
    hazards: ["choking"],
    supervision: "adult-led-prep",
    regulation: false,
    prepByAdult: true,
    competitive: false,
  },
  {
    id: "color-matching-hunt",
    title: "Color Matching Hunt",
    description: "A whole-house hunt for objects that match a colour card.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Cognitive",
    secondarySkills: ["Motor Skills"],
    materials: ["Coloured paper squares", "Basket"],
    steps: [
      "Give your child one colour card at a time; agree which rooms are in bounds.",
      "Hunt together for objects that match.",
      "Sort the finds into colour piles at the end.",
    ],
    energy: "med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "calming-glitter-bottle",
    title: "Calming Glitter Bottle",
    description:
      "Make a sealed glitter bottle (adult seals) and use it as a calm-down visual timer.",
    minAge: 2,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Self-Care",
    secondarySkills: ["Sensory Play"],
    materials: ["Clear bottle", "Warm water", "Glitter glue", "Glitter"],
    steps: [
      "Adult: fill with warm water and glitter glue, add glitter, seal lid firmly (tape or glue the lid).",
      "Shake together and watch the glitter settle.",
      "Practise slow breaths until the glitter settles; put away if the seal fails.",
    ],
    energy: "low",
    hazards: ["choking", "small-parts"],
    supervision: "adult-led-prep",
    regulation: true,
    prepByAdult: true,
    competitive: false,
  },
  {
    id: "obstacle-course",
    title: "Living Room Obstacle Course",
    description: "Gross motor planning with cushions and tunnels.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 20,
    maxMinutes: 30,
    skill: "Motor Skills",
    secondarySkills: ["Cognitive"],
    materials: ["Cushions", "Blanket", "Masking tape"],
    steps: [
      "Build three stations: crawl, jump, balance — clear sharp corners and breakables.",
      "Walk the course together once slowly.",
      "Optional: time a run, or just cheer the finish without a clock if timing stresses your child.",
    ],
    energy: "high",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "dressing-race",
    title: "Dressing Practice Play",
    description: "Practise putting on easy clothes in a playful, low-pressure way.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Self-Care",
    secondarySkills: ["Motor Skills"],
    materials: ["Loose clothes", "Timer"],
    steps: [
      "Lay out one easy garment at a time.",
      "Cheer effort (skip the timer if it adds pressure).",
      "Finish with a mirror check together.",
    ],
    energy: "med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "turn-taking-tower",
    title: "Turn-Taking Tower",
    description: "Building a block tower one turn each.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Social Skills",
    secondarySkills: ["Motor Skills"],
    materials: ["Wooden blocks"],
    steps: [
      "Say 'my turn' and place a block.",
      "Say 'your turn' and wait patiently.",
      "Knock it down together as the reward.",
    ],
    energy: "low-med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "stringing-beads",
    title: "Stringing Beads",
    description: "Thread large beads onto a lace for fine motor practice (supervise closely).",
    minAge: 3,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    secondarySkills: ["Cognitive"],
    materials: ["Large beads (choking-safe size)", "Shoelace or pipe cleaner"],
    steps: [
      "Use only large beads that cannot fit in a choke tube; adult holds the lace.",
      "Show how to push each bead along.",
      "Make a bracelet or keep it as a string — do not leave a loop around the neck unsupervised.",
    ],
    energy: "low-med",
    hazards: ["choking", "small-parts"],
    supervision: "arm-reach",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "playdough-pinch",
    title: "Playdough Pinch",
    description: "Strengthen little fingers by pinching and rolling dough.",
    minAge: 2,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    secondarySkills: ["Sensory Play"],
    materials: ["Playdough", "Cookie cutters"],
    steps: [
      "Roll the dough into small balls (keep dough away from mouths).",
      "Pinch each ball between thumb and finger.",
      "Flatten with a cutter and name the shape.",
    ],
    energy: "low-med",
    hazards: ["choking"],
    supervision: "arm-reach",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "clothespin-drop",
    title: "Clothespin Drop",
    description: "Squeezing clothespins to drop pom-poms into a jar.",
    minAge: 3,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    secondarySkills: ["Cognitive"],
    materials: ["Clothespins", "Pom-poms", "Jar or cup"],
    steps: [
      "Place large pom-poms in a shallow dish (adult stays close).",
      "Use a clothespin to pick up each one.",
      "Drop them into the jar and count together.",
    ],
    energy: "low-med",
    hazards: ["choking", "small-parts"],
    supervision: "arm-reach",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "scooping-and-pouring",
    title: "Scooping and Pouring",
    description:
      "Practise scooping and pouring rice or water between bowls (supervise; wipe spills).",
    minAge: 2,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    secondarySkills: ["Sensory Play"],
    materials: ["Two bowls", "Scoop or cup", "Water or rice"],
    steps: [
      "Fill one bowl with water or rice on a tray.",
      "Scoop from the full bowl into the empty one.",
      "Pour slowly and stop near the top; mop water spills so floors stay safe.",
    ],
    energy: "low-med",
    hazards: ["choking", "water"],
    supervision: "arm-reach",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "threading-pasta",
    title: "Threading Pasta",
    description: "Stringing pasta tubes onto a string for hand-eye coordination.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Tube pasta", "Shoelace", "Tape end"],
    steps: [
      "Tape one end of the string to make it stiff.",
      "Show how to push the pasta through (pasta is for threading, not snacking).",
      "Hang the finished strand as a decoration.",
    ],
    energy: "low-med",
    hazards: ["choking"],
    supervision: "arm-reach",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "sticker-peel",
    title: "Sticker Peel and Stick",
    description: "Removing and placing stickers for fine motor precision.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    secondarySkills: ["Cognitive"],
    materials: ["Dot stickers", "Paper with drawn shapes"],
    steps: [
      "Peel the edge of each sticker up for your child.",
      "Stick one inside each drawn shape.",
      "Count how many stickers are used.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "cutting-practice",
    title: "Cutting Practice Strips",
    description:
      "Adult-supervised scissor practice on thick paper strips with child-safe scissors.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Child-safe scissors", "Thick paper strips", "Tray"],
    steps: [
      "Draw straight lines across the strips; adult stays within arm's reach.",
      "Child holds paper with one hand and cuts away from body with the other.",
      "Drop snipped pieces into a tray; store scissors after.",
    ],
    energy: "low-med",
    hazards: ["scissors"],
    supervision: "arm-reach",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "balance-beam",
    title: "Balance Beam Walk",
    description: "Walking along a low line or tape to practice balance.",
    minAge: 2,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    materials: ["Masking tape", "Floor space"],
    steps: [
      "Make a straight line on the floor with tape; clear clutter.",
      "Walk along the line (side-step or heel-to-toe as able); adult spots younger kids.",
      "Add arms out wide or carry a small toy if ready.",
    ],
    energy: "med",
    supervision: "arm-reach",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "animal-walks",
    title: "Animal Walks",
    description: "Moving like animals to build core and coordination.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Open floor space"],
    steps: [
      "Bear walk on hands and feet for a short distance.",
      "Crab walk with tummy up (stop if wrists hurt).",
      "Frog jump across the room; rest between animals.",
    ],
    energy: "high",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "bean-bag-toss",
    title: "Bean Bag Toss",
    description: "Aiming and throwing into a target.",
    minAge: 2,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Bean bags or rolled socks", "Box or bucket"],
    steps: [
      "Place the target a few steps away.",
      "Toss underhand and watch where it lands.",
      "Move the target closer or farther.",
    ],
    energy: "med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "jumping-jacks",
    title: "Jumping Jacks Count",
    description: "Count together while jumping jacks — or a simpler jump-and-clap version.",
    minAge: 4,
    maxAge: 8,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Motor Skills",
    secondarySkills: ["Cognitive"],
    materials: ["Open space"],
    steps: [
      "Start with arms by your sides (or seated arm taps if jumping is hard today).",
      "Jump and spread arms and legs while counting — messy form is fine.",
      "Try to reach ten together, then rest.",
    ],
    energy: "high",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "simon-says",
    title: "Simon Says Moves",
    description:
      "A listening game: follow movement cues when 'Simon says', and practise pausing when the cue is missing.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    secondarySkills: ["Motor Skills", "Social Skills"],
    materials: ["Open space"],
    steps: [
      "Say 'Simon says touch your toes'.",
      "Add tricky instructions without the cue.",
      "Switch roles so your child leads.",
    ],
    energy: "med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "yoga-poses",
    title: "Yoga Poses for Kids",
    description:
      "Simple, optional poses to stretch and settle the body — skip any pose that feels wrong.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    secondarySkills: ["Self-Care"],
    materials: ["Mat or towel", "Open space"],
    steps: [
      "Try tree pose with one foot on the other ankle (hold a wall if needed).",
      "Hold downward dog for a slow count of five, or choose child's pose instead.",
      "Finish with child's pose and deep breaths.",
    ],
    energy: "low-med",
    supervision: "spot",
    regulation: true,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "tweezer-transfer",
    title: "Tweezer Transfer",
    description: "Moving small objects with tweezers for pincer strength.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    secondarySkills: ["Cognitive"],
    materials: ["Child-safe blunt tweezers", "Large pompoms", "Muffin tin"],
    steps: [
      "Place one pom-pom in each muffin cup; adult stays close.",
      "Use the tweezers to move them to the other side.",
      "Optional: sort by colour if you have different shades.",
    ],
    energy: "low-med",
    hazards: ["choking", "small-parts"],
    supervision: "arm-reach",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "rolling-tunnel",
    title: "Blanket Crawl Tunnel",
    description: "Crawling through a blanket tunnel made from chairs (stabilize chairs first).",
    minAge: 2,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    secondarySkills: ["Sensory Play"],
    materials: ["Two chairs", "Blanket"],
    steps: [
      "Drape the blanket over sturdy chairs; check chairs will not tip.",
      "Crawl through from one side to the other — offer a wide open side if enclosed feels scary.",
      "Place a toy at the end as a reward.",
    ],
    energy: "med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "hopscotch",
    title: "Hopscotch Grid",
    description: "Hopping and balancing on a numbered grid.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    secondarySkills: ["Cognitive"],
    materials: ["Chalk", "Outdoor space or tape"],
    steps: [
      "Draw a 1–10 grid on the ground.",
      "Hop on one foot over single squares (or jump with two feet if balancing is hard).",
      "Land with both feet on the double squares.",
    ],
    energy: "med-high",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "stacking-cups",
    title: "Stacking Cups",
    description: "Building and nesting cups for hand control.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    secondarySkills: ["Cognitive"],
    materials: ["Plastic cups"],
    steps: [
      "Stack the cups into a tower.",
      "Knock them down carefully.",
      "Nest them back inside each other.",
    ],
    energy: "low-med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "hole-punch",
    title: "Hole Punch Fun",
    description: "Punching holes in paper for hand strength.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Single hole punch", "Paper", "Tray"],
    steps: [
      "Draw dots on the paper as targets; keep fingers clear of the punch jaws.",
      "Punch a hole on each dot.",
      "Collect the tiny circles in a tray (keep them away from mouths).",
    ],
    energy: "low",
    hazards: ["choking", "small-parts"],
    supervision: "arm-reach",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "target-throwing",
    title: "Target Throwing",
    description:
      "Throwing soft balls at a floor target (same family as bean-bag toss — keep one or differentiate distance/targets).",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Soft balls", "Target mat or hula hoop"],
    steps: [
      "Place the target on the floor.",
      "Stand behind a line and throw underhand.",
      "Move the line back after each round.",
    ],
    energy: "med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "dancing-freeze",
    title: "Dancing Freeze",
    description: "Moving to music and freezing when it stops.",
    minAge: 2,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    secondarySkills: ["Cognitive", "Social Skills"],
    materials: ["Music player"],
    steps: [
      "Play music and dance together.",
      "Pause the music suddenly.",
      "Freeze in the silliest pose you can hold.",
    ],
    energy: "high",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "textured-walk",
    title: "Textured Walk",
    description: "Walking barefoot over different surfaces for sensory input.",
    minAge: 1,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Sensory Play",
    secondarySkills: ["Motor Skills"],
    materials: ["Towel", "Bubble wrap", "Rug", "Foam mat"],
    steps: [
      "Lay a path of different textures on a clear floor.",
      "Walk slowly and describe each feeling; offer shoes/socks if barefoot is aversive.",
      "Let your child choose the next texture.",
    ],
    energy: "low-med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "scented-playdough",
    title: "Scented Playdough",
    description:
      "Smell and squeeze dough with a light scent — skip scent if smells are hard for your child.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 15,
    maxMinutes: 20,
    skill: "Sensory Play",
    secondarySkills: ["Motor Skills", "Self-Care"],
    materials: ["Playdough", "Vanilla or citrus extract"],
    steps: [
      "Optional: adult adds one drop of scent to the dough (or use unscented).",
      "Guess the smell with eyes open or closed — no tasting.",
      "Roll and squeeze while breathing slowly.",
    ],
    energy: "low",
    hazards: ["allergen-scent", "choking"],
    supervision: "arm-reach",
    regulation: true,
    prepByAdult: true,
    competitive: false,
  },
  {
    id: "water-pouring",
    title: "Water Pouring Station",
    description: "Pouring water between jugs for calm, focused play.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 15,
    maxMinutes: 20,
    skill: "Sensory Play",
    secondarySkills: ["Motor Skills"],
    materials: ["Small jugs", "Water", "Food colouring", "Tray"],
    steps: [
      "Add coloured water to one jug on a deep tray (protect floors/clothes).",
      "Pour carefully into the other.",
      "Stop before it spills and compare levels; wipe spills promptly.",
    ],
    energy: "low-med",
    hazards: ["water", "food-dye"],
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "sensory-bottle",
    title: "Sensory Bottle",
    description: "Watch objects move in a tightly sealed bottle (adult seals; not a chew toy).",
    minAge: 2,
    maxAge: 6,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Sensory Play",
    secondarySkills: ["Self-Care"],
    materials: ["Bottle", "Water", "Small beads", "Glitter"],
    steps: [
      "Adult fills the bottle with water and small items.",
      "Seal the lid tightly with strong tape or glue; check it cannot be opened by the child.",
      "Tip and shake, then watch everything settle.",
    ],
    energy: "low",
    hazards: ["choking", "small-parts"],
    supervision: "adult-led-prep",
    regulation: true,
    prepByAdult: true,
    competitive: false,
  },
  {
    id: "kinetic-sand",
    title: "Kinetic Sand",
    description: "Squeezing and shaping mouldable sand.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 15,
    maxMinutes: 30,
    skill: "Sensory Play",
    secondarySkills: ["Motor Skills"],
    materials: ["Kinetic sand", "Small moulds", "Tray"],
    steps: [
      "Pour sand into a shallow tray (hands only — not for tasting).",
      "Press it into moulds and lift slowly.",
      "Squeeze handfuls and let it flow through fingers.",
    ],
    energy: "low-med",
    supervision: "arm-reach",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "noise-shakers",
    title: "Noise Shakers",
    description:
      "Explore loud and soft sounds with adult-sealed shakers (start quiet; watch for overload).",
    minAge: 2,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Sensory Play",
    secondarySkills: ["Communication"],
    materials: ["Small jars with secure lids", "Rice", "Beans", "Strong tape for lids"],
    steps: [
      "Adult fills two jars with different fillings and tapes lids shut.",
      "Shake gently first; compare the sounds; stop if it feels too loud.",
      "Make a loud-soft pattern together.",
    ],
    energy: "high",
    hazards: ["choking", "loud-sound", "small-parts"],
    supervision: "adult-led-prep",
    regulation: false,
    prepByAdult: true,
    competitive: false,
  },
  {
    id: "sound-matching",
    title: "Sound Matching",
    description: "Match pairs of containers by the sound they make when shaken.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    secondarySkills: ["Sensory Play"],
    materials: [
      "Small sealed containers",
      "Rice",
      "Beans",
      "Pasta (avoid loose coins with young kids)",
    ],
    steps: [
      "Adult makes pairs of identical-sounding sealed containers.",
      "Shake one and listen closely.",
      "Find the container that matches the sound.",
    ],
    energy: "low-med",
    hazards: ["choking", "small-parts"],
    supervision: "spot",
    regulation: false,
    prepByAdult: true,
    competitive: false,
  },
  {
    id: "labeling-hunt",
    title: "Labeling Hunt",
    description: "Finding and naming objects around the room.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Communication",
    secondarySkills: ["Cognitive"],
    materials: ["Picture cards or word labels"],
    steps: [
      "Show a picture card or label.",
      "Search the room for the matching item.",
      "Say the name together when you find it.",
    ],
    energy: "med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "copycat-words",
    title: "Copycat Words",
    description: "Copy silly sounds or word chains — gestures or device words count too.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Communication",
    materials: ["No materials needed"],
    steps: [
      "Say a simple word or sound like 'pop'.",
      "Invite a copy in any mode your child uses (voice, sign, AAC).",
      "Make a chain of three and take turns.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "story-sequencing",
    title: "Story Sequencing",
    description: "Put story pictures in order, then retell what happened.",
    minAge: 4,
    maxAge: 7,
    minMinutes: 15,
    maxMinutes: 20,
    skill: "Cognitive",
    secondarySkills: ["Communication"],
    materials: ["Story picture cards"],
    steps: [
      "Read the story first.",
      "Mix the cards and lay them out.",
      "Put them in order and retell the story.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "matching-pairs",
    title: "Matching Pairs",
    description:
      "Turn cards to find matching pictures (simpler/cooperative cousin of Memory Card Game).",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    materials: ["Picture cards"],
    steps: [
      "Shuffle and lay cards face down.",
      "Turn two cards at a time.",
      "Keep the pair if they match.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "pattern-building",
    title: "Pattern Building",
    description: "Continuing colour or shape patterns with blocks.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    secondarySkills: ["Motor Skills"],
    materials: ["Coloured blocks or beads"],
    steps: [
      "Start a simple pattern: red, blue, red, blue.",
      "Ask what comes next.",
      "Let your child make their own pattern.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "memory-cards",
    title: "Memory Card Game",
    description: "Remembering card positions to find matching pairs.",
    minAge: 4,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    secondarySkills: ["Social Skills"],
    materials: ["Memory card set"],
    steps: [
      "Lay cards face down in a grid.",
      "Take turns turning two cards.",
      "Celebrate matches together (skip scorekeeping if competition stresses your child).",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: true,
  },
  {
    id: "sorting-size",
    title: "Sorting by Size",
    description: "Ordering objects from smallest to largest.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    materials: ["4–6 similar objects in different sizes"],
    steps: [
      "Mix the objects together.",
      "Find the smallest and place it first.",
      "Line them up from small to big.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "pass-the-ball",
    title: "Pass the Ball",
    description: "Rolling a ball back and forth to practise sharing space.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Social Skills",
    secondarySkills: ["Motor Skills"],
    materials: ["Soft ball"],
    steps: [
      "Sit facing each other.",
      "Roll the ball and say 'your turn'.",
      "Wait for it to come back before rolling again.",
    ],
    energy: "low-med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "greeting-circle",
    title: "Greeting Circle",
    description:
      "Practise hellos in a circle using any greeting style that feels okay (wave, words, AAC — eye contact optional).",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Social Skills",
    secondarySkills: ["Communication"],
    materials: ["Floor space"],
    steps: [
      "Sit in a circle facing each other (or side-by-side if facing is hard).",
      "Greet the person next to you in a comfortable way.",
      "Optional: add a high five or name greeting — skip anything that feels forced.",
    ],
    energy: "med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "sharing-basket",
    title: "Sharing Basket",
    description: "Taking turns choosing items from a shared basket.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Social Skills",
    materials: ["Basket", "Small toys"],
    steps: [
      "Place a few toys in the basket.",
      "Take turns choosing one.",
      "Say thank you when you receive your turn.",
    ],
  },
  {
    id: "button-frame",
    title: "Button Frame",
    description: "Practise buttoning on a fabric frame the adult prepares ahead of time.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Self-Care",
    secondarySkills: ["Motor Skills"],
    materials: [
      "Prepared button frame (old shirt/fabric with large buttons)",
      "Large buttons (secured)",
    ],
    steps: [
      "Adult prep (ahead): sew large buttons on one side and cut slots on the other.",
      "Show how to push a button through its slot.",
      "Let your child practise; keep loose buttons away from mouths.",
    ],
    energy: "low",
    hazards: ["choking", "small-parts"],
    supervision: "adult-led-prep",
    regulation: false,
    prepByAdult: true,
    competitive: false,
  },
  {
    id: "shoe-lacing",
    title: "Shoe Lacing Practice",
    description:
      "Practise threading and tying on a shoe or lacing card — start with threading if bows are too hard.",
    minAge: 4,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Self-Care",
    secondarySkills: ["Motor Skills"],
    materials: ["Shoe or cardboard lacing card", "Shoelace"],
    steps: [
      "Thread the lace up through each hole.",
      "Cross the laces and pull tight.",
      "If ready, make two loops and cross them for a bow — or stop at a knot and celebrate.",
    ],
    energy: "low-med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "setting-table",
    title: "Setting the Table",
    description: "Placing plates and cutlery in the right spots.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Self-Care",
    secondarySkills: ["Cognitive"],
    materials: ["Unbreakable plate", "Cup", "Fork", "Spoon"],
    steps: [
      "Place the plate in the centre.",
      "Put the fork on the left and spoon on the right.",
      "Add the cup above the plate.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "hand-washing",
    title: "Hand Washing Steps",
    description: "Following a step-by-step hand washing routine.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Self-Care",
    materials: ["Sink", "Soap", "Towel"],
    steps: [
      "Wet hands with comfortable warm water and add soap.",
      "Rub palms, backs, and between fingers while counting.",
      "Rinse and dry with a towel.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "finger-paint",
    title: "Finger Paint Patterns",
    description:
      "Make marks with washable finger paint to explore colour and movement (supervise tasting).",
    minAge: 2,
    maxAge: 4,
    minMinutes: 15,
    maxMinutes: 20,
    skill: "Sensory Play",
    secondarySkills: ["Motor Skills", "Cognitive"],
    materials: ["Washable finger paint", "Paper", "Wipes"],
    steps: [
      "Dip one finger in washable paint (smock/wipes ready).",
      "Make dots, lines, and circles on paper.",
      "Name the colours and shapes together.",
    ],
    energy: "med",
    hazards: ["food-dye"],
    supervision: "arm-reach",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "brushing-hair",
    title: "Brushing Hair Practice",
    description: "Gentle brushing practice on a doll or own hair — stop if it feels too much.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Self-Care",
    secondarySkills: ["Sensory Play"],
    materials: ["Hairbrush", "Doll or mirror"],
    steps: [
      "Start at the ends and hold the hair above tangles (try doll first if head touch is hard).",
      "Brush gently from bottom toward top.",
      "Look in the mirror if comfortable; praise any attempt.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: true,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "balloon-tap",
    title: "Balloon Tap",
    description:
      "Keep a balloon in the air with gentle taps (adult inflates; watch for latex allergy and popped pieces).",
    minAge: 3,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    secondarySkills: ["Social Skills"],
    materials: ["Balloon (check latex allergy; mylar alternative if needed)"],
    steps: [
      "Adult blows up the balloon and ties it; check for allergies.",
      "Tap it up before it lands; do not bite or chew the balloon.",
      "Count taps together; throw away any popped pieces immediately.",
    ],
    energy: "med-high",
    hazards: ["latex", "choking"],
    supervision: "arm-reach",
    regulation: false,
    prepByAdult: true,
    competitive: false,
  },
  {
    id: "face-parts-game",
    title: "Face Parts Game",
    description: "Placing features on a blank face to learn body parts.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Communication",
    secondarySkills: ["Cognitive"],
    materials: ["Paper face outline", "Stickers or cut-out features"],
    steps: [
      "Point to each place where eyes, nose, and mouth go.",
      "Stick the features on the face.",
      "Name each part and make the same face.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "puzzle-time",
    title: "Puzzle Time",
    description:
      "Complete an age-fit puzzle for problem-solving (knob puzzles for younger kids; jigsaws when ready).",
    minAge: 2,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Cognitive",
    secondarySkills: ["Motor Skills"],
    materials: ["Age-appropriate puzzle"],
    steps: [
      "Choose a puzzle that matches your child's current level; turn pieces picture-side up.",
      "For jigsaws: find corners/edges first. For knob puzzles: match picture to board.",
      "Match colours and shapes to finish; offer help before frustration peaks.",
    ],
    energy: "low-med",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
  {
    id: "emotional-cards",
    title: "Emotion Cards",
    description: "Matching feelings words to facial expressions.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Social Skills",
    secondarySkills: ["Communication"],
    materials: ["Emotion cards", "Mirror"],
    steps: [
      "Show a card and read the feeling word.",
      "Make that face in the mirror.",
      "Talk about a time you felt that way.",
    ],
    energy: "low",
    supervision: "spot",
    regulation: false,
    prepByAdult: false,
    competitive: false,
  },
];

export function findActivity(id: string, list: Activity[] = ACTIVITIES): Activity | undefined {
  const canonical = canonicalActivityId(id);
  return list.find((a) => a.id === canonical);
}

export function activityHasSkill(activity: Activity, skill: Skill): boolean {
  return activity.skill === skill || (activity.secondarySkills?.includes(skill) ?? false);
}

export const skillTone: Record<Skill, string> = {
  "Sensory Play": "tag-sensory",
  "Motor Skills": "tag-motor",
  Communication: "tag-communication",
  "Social Skills": "tag-social",
  Cognitive: "tag-cognitive",
  "Self-Care": "tag-selfcare",
};
