export type Skill =
  | "Sensory Play"
  | "Motor Skills"
  | "Communication"
  | "Social Skills"
  | "Cognitive"
  | "Self-Care";

export const SKILLS: Skill[] = [
  "Sensory Play",
  "Motor Skills",
  "Communication",
  "Social Skills",
  "Cognitive",
  "Self-Care",
];

export function formatActivityDuration(minMinutes: number, maxMinutes: number) {
  return minMinutes === maxMinutes ? `${minMinutes} mins` : `${minMinutes}-${maxMinutes} mins`;
}

export type Activity = {
  id: string;
  title: string;
  description: string;
  minAge: number;
  maxAge: number;
  minMinutes: number;
  maxMinutes: number;
  skill: Skill;
  materials: string[];
  steps: string[];
};

export const ACTIVITIES: Activity[] = [
  {
    id: "sensory-rice-bin",
    title: "Sensory Rice Bin",
    description: "A calming sensory activity using colored rice to explore textures.",
    minAge: 1,
    maxAge: 3,
    minMinutes: 15,
    maxMinutes: 30,
    skill: "Sensory Play",
    materials: ["Dry rice", "Food colouring", "Shallow bin", "Scoops & cups"],
    steps: [
      "Dye rice with a few drops of food colouring and let it dry.",
      "Pour into a shallow bin and add scoops and small cups.",
      "Sit alongside your child and narrate the textures you feel.",
    ],
  },
  {
    id: "tape-rescue",
    title: "Tape Rescue",
    description: "Fine motor activity peeling tape off toys.",
    minAge: 2,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    materials: ["Masking tape", "Favourite small toys"],
    steps: [
      "Tape a few toys down to a table or tray.",
      "Invite your child to free the toys by peeling the tape.",
      "Celebrate each rescue with a high five.",
    ],
  },
  {
    id: "mirror-emotions",
    title: "Mirror Emotions",
    description: "Learning to identify and mimic facial expressions.",
    minAge: 3,
    maxAge: 5,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Communication",
    materials: ["A mirror"],
    steps: [
      "Sit together in front of a mirror.",
      "Make a face and name the feeling out loud.",
      "Take turns copying each other's expressions.",
    ],
  },
  {
    id: "deep-pressure-sandwich",
    title: "Deep Pressure Sandwich",
    description: "Deep pressure therapy using pillows for regulation.",
    minAge: 2,
    maxAge: 8,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Sensory Play",
    materials: ["Two large cushions"],
    steps: [
      "Ask your child to lie between two cushions.",
      "Press gently and evenly, checking in constantly.",
      "Stop the moment they ask, and count the squeezes together.",
    ],
  },
  {
    id: "story-time-props",
    title: "Story Time with Props",
    description: "Using objects to bring a story to life.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 20,
    maxMinutes: 20,
    skill: "Communication",
    materials: ["Picture book", "Matching toys or household items"],
    steps: [
      "Pick a short familiar story.",
      "Hand your child a prop for each character.",
      "Pause and let them fill in the next line.",
    ],
  },
  {
    id: "rhyming-match",
    title: "Rhyming Match",
    description: "Phonological awareness development.",
    minAge: 4,
    maxAge: 7,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Communication",
    materials: ["Picture cards or drawings"],
    steps: [
      "Lay out six picture cards in three rhyming pairs.",
      "Say each word slowly and stretch the ending sound.",
      "Let your child pair the ones that sound the same.",
    ],
  },
  {
    id: "puppet-conversation",
    title: "Puppet Conversation",
    description: "Encouraging verbal interaction through a proxy.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Communication",
    materials: ["Sock puppet or soft toy"],
    steps: [
      "Introduce the puppet with a silly voice.",
      "Have the puppet ask simple questions.",
      "Let your child answer the puppet, not you.",
    ],
  },
  {
    id: "interactive-bubble-chase",
    title: "Interactive Bubble Chase",
    description: "Joint attention and turn-taking fun.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Social Skills",
    materials: ["Bubble mix", "Wand"],
    steps: [
      "Blow a few bubbles and wait for eye contact.",
      "Pause until your child signals for more.",
      "Swap roles and let them try blowing.",
    ],
  },
  {
    id: "shadow-puppets",
    title: "Shadow Puppets",
    description: "Exploring light and shadow to build imagination.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Cognitive",
    materials: ["Torch", "Blank wall"],
    steps: [
      "Dim the room and shine a torch at the wall.",
      "Make animal shapes and guess each other's shadow.",
      "Invent a short story with two shadow characters.",
    ],
  },
  {
    id: "zip-loc-bag-painting",
    title: "Zip-Loc Bag Painting",
    description: "Mess-free sensory painting.",
    minAge: 1,
    maxAge: 3,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Sensory Play",
    materials: ["Zip-loc bag", "Two paint colours", "Tape"],
    steps: [
      "Squirt paint into the bag and seal it tightly.",
      "Tape the bag to a window or table.",
      "Let your child squish and swirl the colours.",
    ],
  },
  {
    id: "color-matching-hunt",
    title: "Color Matching Hunt",
    description: "A whole-house hunt for objects that match a colour card.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Cognitive",
    materials: ["Coloured paper squares", "Basket"],
    steps: [
      "Give your child one colour card at a time.",
      "Hunt the room for objects that match.",
      "Sort the finds into colour piles at the end.",
    ],
  },
  {
    id: "calming-glitter-bottle",
    title: "Calming Glitter Bottle",
    description: "A self-regulation tool your child helps build.",
    minAge: 2,
    maxAge: 8,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Self-Care",
    materials: ["Clear bottle", "Warm water", "Glitter glue", "Glitter"],
    steps: [
      "Fill the bottle with warm water and glitter glue.",
      "Add glitter, seal the lid, and shake.",
      "Use it as a timer for calm breathing.",
    ],
  },
  {
    id: "obstacle-course",
    title: "Living Room Obstacle Course",
    description: "Gross motor planning with cushions and tunnels.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 20,
    maxMinutes: 30,
    skill: "Motor Skills",
    materials: ["Cushions", "Blanket", "Masking tape"],
    steps: [
      "Build three stations: crawl, jump, balance.",
      "Walk the course together once slowly.",
      "Time each run and cheer the finish.",
    ],
  },
  {
    id: "dressing-race",
    title: "Dressing Race",
    description: "Practising independent dressing in a playful way.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Self-Care",
    materials: ["Loose clothes", "Timer"],
    steps: [
      "Lay out one easy garment at a time.",
      "Set a gentle timer and cheer them on.",
      "Finish with a mirror check together.",
    ],
  },
  {
    id: "turn-taking-tower",
    title: "Turn-Taking Tower",
    description: "Building a block tower one turn each.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Social Skills",
    materials: ["Wooden blocks"],
    steps: [
      "Say 'my turn' and place a block.",
      "Say 'your turn' and wait patiently.",
      "Knock it down together as the reward.",
    ],
  },
  {
    id: "stringing-beads",
    title: "Stringing Beads",
    description: "Threading beads onto a shoelace for fine motor control.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    materials: ["Large beads", "Shoelace or pipe cleaner"],
    steps: [
      "Hold the lace steady for your child.",
      "Show them how to push the bead along.",
      "Make a bracelet or necklace when finished.",
    ],
  },
  {
    id: "playdough-pinch",
    title: "Playdough Pinch",
    description: "Strengthen little fingers by pinching and rolling dough.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Playdough", "Cookie cutters"],
    steps: [
      "Roll the dough into small balls.",
      "Pinch each ball between thumb and finger.",
      "Flatten with a cutter and name the shape.",
    ],
  },
  {
    id: "clothespin-drop",
    title: "Clothespin Drop",
    description: "Squeezing clothespins to drop pom-poms into a jar.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Clothespins", "Pom-poms", "Jar or cup"],
    steps: [
      "Place pom-poms in a shallow dish.",
      "Use a clothespin to pick up each one.",
      "Drop them into the jar and count together.",
    ],
  },
  {
    id: "scooping-and-pouring",
    title: "Scooping and Pouring",
    description: "Transferring water or rice between containers.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    materials: ["Two bowls", "Scoop or cup", "Water or rice"],
    steps: [
      "Fill one bowl with water or rice.",
      "Scoop from the full bowl into the empty one.",
      "Pour slowly and stop when it reaches the top.",
    ],
  },
  {
    id: "threading-pasta",
    title: "Threading Pasta",
    description: "Stringing pasta tubes onto a string for hand-eye coordination.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Tube pasta", "Shoelace", "Tape end"],
    steps: [
      "Tape one end of the string to make it stiff.",
      "Show how to push the pasta through.",
      "Hang the finished strand as a decoration.",
    ],
  },
  {
    id: "sticker-peel",
    title: "Sticker Peel and Stick",
    description: "Removing and placing stickers for fine motor precision.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Dot stickers", "Paper with drawn shapes"],
    steps: [
      "Peel the edge of each sticker up for your child.",
      "Stick one inside each drawn shape.",
      "Count how many stickers are used.",
    ],
  },
  {
    id: "cutting-practice",
    title: "Cutting Practice Strips",
    description: "Safe scissor practice on thick paper strips.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Child-safe scissors", "Thick paper strips", "Tray"],
    steps: [
      "Draw straight lines across the strips.",
      "Hold the paper with one hand and cut with the other.",
      "Drop the snipped pieces into a tray.",
    ],
  },
  {
    id: "balance-beam",
    title: "Balance Beam Walk",
    description: "Walking along a low line or tape to practice balance.",
    minAge: 2,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    materials: ["Masking tape", "Floor space"],
    steps: [
      "Make a straight line on the floor with tape.",
      "Walk heel-to-toe along the line.",
      "Add arms out wide or carry a small toy.",
    ],
  },
  {
    id: "animal-walks",
    title: "Animal Walks",
    description: "Moving like animals to build core and coordination.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Open floor space"],
    steps: [
      "Bear walk on hands and feet.",
      "Crab walk with tummy up.",
      "Frog jump across the room.",
    ],
  },
  {
    id: "bean-bag-toss",
    title: "Bean Bag Toss",
    description: "Aiming and throwing into a target.",
    minAge: 2,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Bean bags or rolled socks", "Box or bucket"],
    steps: [
      "Place the target a few steps away.",
      "Toss underhand and watch where it lands.",
      "Move the target closer or farther.",
    ],
  },
  {
    id: "jumping-jacks",
    title: "Jumping Jacks Count",
    description: "Counting while doing jumping jacks for rhythm and body awareness.",
    minAge: 4,
    maxAge: 8,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Motor Skills",
    materials: ["Open space"],
    steps: [
      "Start with arms by your sides.",
      "Jump and spread arms and legs while counting.",
      "Try to reach ten together.",
    ],
  },
  {
    id: "simon-says",
    title: "Simon Says Moves",
    description: "Following movement instructions to build listening and control.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Open space"],
    steps: [
      "Say 'Simon says touch your toes'.",
      "Add tricky instructions without the cue.",
      "Switch roles so your child leads.",
    ],
  },
  {
    id: "yoga-poses",
    title: "Yoga Poses for Kids",
    description: "Simple poses to stretch and calm the body.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    materials: ["Mat or towel", "Open space"],
    steps: [
      "Try tree pose with one foot on the other ankle.",
      "Hold downward dog for a slow count of five.",
      "Finish with child's pose and deep breaths.",
    ],
  },
  {
    id: "tweezer-transfer",
    title: "Tweezer Transfer",
    description: "Moving small objects with tweezers for pincer strength.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Tweezers", "Small pompoms", "Muffin tin"],
    steps: [
      "Place one pom-pom in each muffin cup.",
      "Use the tweezers to move them to the other side.",
      "Sort by colour if you have different shades.",
    ],
  },
  {
    id: "rolling-tunnel",
    title: "Rolling Crawl Tunnel",
    description: "Crawling through a tunnel made from chairs and a blanket.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Two chairs", "Blanket"],
    steps: [
      "Drape the blanket over the chairs to make a tunnel.",
      "Crawl through from one side to the other.",
      "Place a toy at the end as a reward.",
    ],
  },
  {
    id: "hopscotch",
    title: "Hopscotch Grid",
    description: "Hopping and balancing on a numbered grid.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Chalk", "Outdoor space or tape"],
    steps: [
      "Draw a 1–10 grid on the ground.",
      "Hop on one foot over single squares.",
      "Land with both feet on the double squares.",
    ],
  },
  {
    id: "stacking-cups",
    title: "Stacking Cups",
    description: "Building and nesting cups for hand control.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Plastic cups"],
    steps: [
      "Stack the cups into a tower.",
      "Knock them down carefully.",
      "Nest them back inside each other.",
    ],
  },
  {
    id: "hole-punch",
    title: "Hole Punch Fun",
    description: "Punching holes in paper for hand strength.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Single hole punch", "Paper", "Tray"],
    steps: [
      "Draw dots on the paper as targets.",
      "Punch a hole on each dot.",
      "Collect the tiny circles in a tray.",
    ],
  },
  {
    id: "target-throwing",
    title: "Target Throwing",
    description: "Throwing soft balls at a target to practice aim.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Soft balls", "Target mat or hula hoop"],
    steps: [
      "Place the target on the floor.",
      "Stand behind a line and throw underhand.",
      "Move the line back after each round.",
    ],
  },
  {
    id: "dancing-freeze",
    title: "Dancing Freeze",
    description: "Moving to music and freezing when it stops.",
    minAge: 2,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Music player"],
    steps: [
      "Play music and dance together.",
      "Pause the music suddenly.",
      "Freeze in the silliest pose you can hold.",
    ],
  },
  {
    id: "textured-walk",
    title: "Textured Walk",
    description: "Walking barefoot over different surfaces for sensory input.",
    minAge: 1,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Sensory Play",
    materials: ["Towel", "Bubble wrap", "Rug", "Foam mat"],
    steps: [
      "Lay a path of different textures.",
      "Walk slowly and describe each feeling.",
      "Let your child choose the next texture.",
    ],
  },
  {
    id: "scented-playdough",
    title: "Scented Playdough",
    description: "Smell and squeeze dough with calming scents.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 15,
    maxMinutes: 20,
    skill: "Sensory Play",
    materials: ["Playdough", "Vanilla or citrus extract"],
    steps: [
      "Add a drop of scent to the dough.",
      "Close your eyes and guess the smell.",
      "Roll and squeeze while breathing slowly.",
    ],
  },
  {
    id: "water-pouring",
    title: "Water Pouring Station",
    description: "Pouring water between jugs for calm, focused play.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 15,
    maxMinutes: 20,
    skill: "Sensory Play",
    materials: ["Small jugs", "Water", "Food colouring", "Tray"],
    steps: [
      "Add coloured water to one jug.",
      "Pour carefully into the other.",
      "Stop before it spills and compare levels.",
    ],
  },
  {
    id: "sensory-bottle",
    title: "Sensory Bottle",
    description: "Watching objects move slowly in a sealed bottle.",
    minAge: 1,
    maxAge: 6,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Sensory Play",
    materials: ["Bottle", "Water", "Small beads", "Glitter"],
    steps: [
      "Fill the bottle with water and small items.",
      "Seal the lid tightly with tape.",
      "Tip and shake, then watch everything settle.",
    ],
  },
  {
    id: "kinetic-sand",
    title: "Kinetic Sand",
    description: "Squeezing and shaping mouldable sand.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 15,
    maxMinutes: 30,
    skill: "Sensory Play",
    materials: ["Kinetic sand", "Small moulds", "Tray"],
    steps: [
      "Pour sand into a shallow tray.",
      "Press it into moulds and lift slowly.",
      "Squeeze handfuls and let it flow through fingers.",
    ],
  },
  {
    id: "noise-shakers",
    title: "Noise Shakers",
    description: "Making shakers and exploring loud and soft sounds.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Sensory Play",
    materials: ["Small jars", "Rice", "Beans", "Beads"],
    steps: [
      "Fill two jars with different fillings.",
      "Shake each and compare the sounds.",
      "Make a loud-soft pattern together.",
    ],
  },
  {
    id: "sound-matching",
    title: "Sound Matching",
    description: "Matching pairs of hidden sound containers.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Communication",
    materials: ["Small sealed containers", "Rice", "Beans", "Coins"],
    steps: [
      "Make pairs of identical-sounding containers.",
      "Shake one and listen closely.",
      "Find the container that matches the sound.",
    ],
  },
  {
    id: "labeling-hunt",
    title: "Labeling Hunt",
    description: "Finding and naming objects around the room.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Communication",
    materials: ["Picture cards or word labels"],
    steps: [
      "Show a picture card or label.",
      "Search the room for the matching item.",
      "Say the name together when you find it.",
    ],
  },
  {
    id: "copycat-words",
    title: "Copycat Words",
    description: "Repeating silly sound chains to build speech imitation.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Communication",
    materials: ["No materials needed"],
    steps: [
      "Say a simple word like 'pop'.",
      "Ask your child to copy you.",
      "Make a chain of three words and take turns.",
    ],
  },
  {
    id: "story-sequencing",
    title: "Story Sequencing",
    description: "Ordering picture cards to retell a familiar story.",
    minAge: 4,
    maxAge: 7,
    minMinutes: 15,
    maxMinutes: 20,
    skill: "Communication",
    materials: ["Story picture cards"],
    steps: [
      "Read the story first.",
      "Mix the cards and lay them out.",
      "Put them in order and retell the story.",
    ],
  },
  {
    id: "matching-pairs",
    title: "Matching Pairs",
    description: "Memory game turning cards to find matching pictures.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    materials: ["Picture cards"],
    steps: [
      "Shuffle and lay cards face down.",
      "Turn two cards at a time.",
      "Keep the pair if they match.",
    ],
  },
  {
    id: "pattern-building",
    title: "Pattern Building",
    description: "Continuing colour or shape patterns with blocks.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    materials: ["Coloured blocks or beads"],
    steps: [
      "Start a simple pattern: red, blue, red, blue.",
      "Ask what comes next.",
      "Let your child make their own pattern.",
    ],
  },
  {
    id: "memory-cards",
    title: "Memory Card Game",
    description: "Remembering card positions to find matching pairs.",
    minAge: 4,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    materials: ["Memory card set"],
    steps: [
      "Lay cards face down in a grid.",
      "Turn two cards on each turn.",
      "The player with the most pairs wins.",
    ],
  },
  {
    id: "sorting-size",
    title: "Sorting by Size",
    description: "Ordering objects from smallest to largest.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    materials: ["Three similar objects in different sizes"],
    steps: [
      "Mix the objects together.",
      "Find the smallest and place it first.",
      "Line them up from small to big.",
    ],
  },
  {
    id: "pass-the-ball",
    title: "Pass the Ball",
    description: "Rolling a ball back and forth to practise sharing space.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Social Skills",
    materials: ["Soft ball"],
    steps: [
      "Sit facing each other.",
      "Roll the ball and say 'your turn'.",
      "Wait for it to come back before rolling again.",
    ],
  },
  {
    id: "greeting-circle",
    title: "Greeting Circle",
    description: "Practising hellos and eye contact in a circle.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Social Skills",
    materials: ["Floor space"],
    steps: [
      "Sit in a circle facing each other.",
      "Wave and say hello to the person next to you.",
      "Add a high five or name greeting.",
    ],
  },
  {
    id: "sharing-basket",
    title: "Sharing Basket",
    description: "Taking turns choosing items from a shared basket.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Social Skills",
    materials: ["Basket", "Small toys"],
    steps: [
      "Place a few toys in the basket.",
      "Take turns choosing one.",
      "Say thank you when you receive your turn.",
    ],
  },
  {
    id: "button-frame",
    title: "Button Frame",
    description: "Pushing buttons through fabric slots for dressing skills.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Self-Care",
    materials: ["Old shirt or fabric", "Large buttons", "Needle and thread"],
    steps: [
      "Sew buttons onto one side of the fabric.",
      "Cut slots on the other side.",
      "Practice pushing each button through its slot.",
    ],
  },
  {
    id: "shoe-lacing",
    title: "Shoe Lacing Practice",
    description: "Threading laces through a practice board or shoe.",
    minAge: 4,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Self-Care",
    materials: ["Shoe or cardboard lacing card", "Shoelace"],
    steps: [
      "Thread the lace up through each hole.",
      "Cross the laces and pull tight.",
      "Make two loops and cross them to tie a bow.",
    ],
  },
  {
    id: "setting-table",
    title: "Setting the Table",
    description: "Placing plates and cutlery in the right spots.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Self-Care",
    materials: ["Plate", "Cup", "Fork", "Spoon"],
    steps: [
      "Place the plate in the centre.",
      "Put the fork on the left and spoon on the right.",
      "Add the cup above the plate.",
    ],
  },
  {
    id: "hand-washing",
    title: "Hand Washing Steps",
    description: "Following a step-by-step hand washing routine.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Self-Care",
    materials: ["Sink", "Soap", "Towel"],
    steps: [
      "Wet hands and add soap.",
      "Rub palms, backs, and between fingers while counting.",
      "Rinse and dry with a towel.",
    ],
  },
  {
    id: "finger-paint",
    title: "Finger Paint Patterns",
    description: "Making marks with fingers to explore colour and movement.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 15,
    maxMinutes: 20,
    skill: "Sensory Play",
    materials: ["Washable finger paint", "Paper", "Wipes"],
    steps: [
      "Dip one finger in paint.",
      "Make dots, lines, and circles on paper.",
      "Name the colours and shapes together.",
    ],
  },
  {
    id: "brushing-hair",
    title: "Brushing Hair Practice",
    description: "Brushing a doll or their own hair with gentle strokes.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Self-Care",
    materials: ["Hairbrush", "Doll or mirror"],
    steps: [
      "Start at the ends and hold the hair above tangles.",
      "Brush gently from bottom to top.",
      "Look in the mirror and practise a smile.",
    ],
  },
  {
    id: "balloon-tap",
    title: "Balloon Tap",
    description: "Keeping a balloon in the air using gentle taps.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Balloon"],
    steps: [
      "Blow up a balloon and release it gently.",
      "Use hands to tap it up before it lands.",
      "Count how many taps you can make together.",
    ],
  },
  {
    id: "face-parts-game",
    title: "Face Parts Game",
    description: "Placing features on a blank face to learn body parts.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Communication",
    materials: ["Paper face outline", "Stickers or cut-out features"],
    steps: [
      "Point to each place where eyes, nose, and mouth go.",
      "Stick the features on the face.",
      "Name each part and make the same face.",
    ],
  },
  {
    id: "puzzle-time",
    title: "Puzzle Time",
    description: "Completing simple puzzles for problem-solving.",
    minAge: 2,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Cognitive",
    materials: ["Age-appropriate puzzle"],
    steps: [
      "Turn all pieces picture-side up.",
      "Find the corner and edge pieces first.",
      "Match colours and shapes to fill the centre.",
    ],
  },
  {
    id: "emotional-cards",
    title: "Emotion Cards",
    description: "Matching feelings words to facial expressions.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Social Skills",
    materials: ["Emotion cards", "Mirror"],
    steps: [
      "Show a card and read the feeling word.",
      "Make that face in the mirror.",
      "Talk about a time you felt that way.",
    ],
  },
];

export const skillTone: Record<Skill, string> = {
  "Sensory Play": "tag-sensory",
  "Motor Skills": "tag-motor",
  Communication: "tag-communication",
  "Social Skills": "tag-social",
  Cognitive: "tag-cognitive",
  "Self-Care": "tag-selfcare",
};
