/** English UI copy. Keep keys stable so a later NL file can mirror them. */
export const familyCopy = {
  childrenTitle: "Children",
  childrenSubtitle: "A first name and age band — nothing medical.",
  childrenEmpty: "Add a child to share a day plan with family and therapists.",
  addChild: "Add a child",
  childNameLabel: "First name",
  childNameHint: "First name only. No surname needed.",
  childNamePlaceholder: "e.g. Nora",
  ageBandLabel: "Age band",
  saveChild: "Save child",
  inviteTitle: "Invite",
  inviteSubtitle: "They will use this email to sign in to Synlumae.",
  inviteEmailLabel: "Email",
  inviteRoleLabel: "Their role",
  sendInvite: "Create invite link",
  copyLink: "Copy invite link",
  linkCopied: "Invite link copied",
  pendingInvites: "Waiting to accept",
  peopleOnChild: "People who can see this plan",
  you: "You",
  owner: "Owner",
  scheduleTitle: "Schedule",
  scheduleSubtitle: "One shared day at a time",
  pickChild: "Choose a child to see today’s plan.",
  addChildCta: "Add a child",
  noPlan: "No plan for this day yet.",
  startAfternoon: "Start a 1-hour afternoon plan",
  addBlock: "Add a time block",
  blockTitle: "What we’ll do",
  blockNotes: "Notes (optional)",
  blockTime: "Start",
  blockMinutes: "Minutes",
  blockActivity: "Link an activity (optional)",
  saveBlock: "Add to plan",
  deletePlan: "Delete this day’s plan",
  checkOffHint: "Tick when it’s done. Everyone on this child can see that.",
  privacyNote:
    "We store a first name, an age band, the people you invite, and the day’s plan. We do not ask for medical diagnoses.",
  localModeBanner:
    "This plan stays on this device. Sharing with another person needs a signed-in account on synlumae.com.",
  uninvited: "You don’t have access to this child.",
  caregiverReadOnly: "You can tick activities as done. Ask a parent to change the plan.",
  therapistNoInvite: "Only a parent can invite other people.",
  acceptTitle: "Join this child’s plan",
  acceptBody: "Sign in with the invited email to see the shared day plan.",
  acceptCta: "Accept invite",
  acceptWrongEmail: "Sign in with the email this invite was sent to.",
  accepted: "You’re in. Open the schedule to see the plan.",
  removePerson: "Remove",
  cancelInvite: "Cancel",
  noActivity: "No activity link",
} as const;

export type FamilyCopyKey = keyof typeof familyCopy;
