// Generated by scripts/bundle-share-api.mjs. Do not edit.

// src/lib/share/errors.ts
var ShareError = class extends Error {
  status;
  code;
  constructor(status, code, message) {
    super(message);
    this.name = "ShareError";
    this.status = status;
    this.code = code;
  }
};

// src/lib/share/mail.ts
function clip(message) {
  return message.replace(/\s+/g, " ").trim().slice(0, 240);
}
function classify(err) {
  const row = err;
  const detail = row?.errors?.[0]?.longMessage || row?.errors?.[0]?.message || (err instanceof Error ? err.message : "") || "Clerk could not send the email.";
  const message = clip(detail);
  const lower = message.toLowerCase();
  if (lower.includes("redirect") || lower.includes("not allowed")) {
    return { sent: false, code: "redirect_blocked", message };
  }
  if (lower.includes("exist") || lower.includes("taken") || lower.includes("already") || row?.errors?.[0]?.code === "form_identifier_exists") {
    return { sent: false, code: "already_user", message };
  }
  return { sent: false, code: "clerk_error", message };
}
async function sendClerkInvitation(input) {
  if (!input.secretKey) {
    return {
      sent: false,
      code: "not_configured",
      message: "CLERK_SECRET_KEY is not set on this preview."
    };
  }
  try {
    const { createClerkClient } = await import("@clerk/backend");
    const clerk = createClerkClient({ secretKey: input.secretKey });
    await clerk.invitations.createInvitation({
      emailAddress: input.email,
      redirectUrl: input.redirectUrl,
      notify: true,
      ignoreExisting: true,
      expiresInDays: 30,
      publicMetadata: { synlumaeInvite: input.token }
    });
    return { sent: true, code: "sent", message: "Invitation email sent." };
  } catch (err) {
    console.error("clerk invitation", err);
    return classify(err);
  }
}

// src/lib/calendar/permissions.ts
function canEditPlan(role) {
  return role === "therapist" || role === "caregiver";
}
function canInvite(role) {
  return role === "therapist" || role === "caregiver";
}
function inviteRolesFor(actor) {
  if (actor === "therapist") return ["caregiver"];
  if (actor === "caregiver") return ["helper"];
  return [];
}
function membershipOnChild(memberships, childId, personId) {
  return memberships.find(
    (m) => m.childId === childId && m.personId === personId && m.status === "active"
  ) ?? null;
}

// src/lib/calendar/types.ts
var AGE_BANDS = [
  { id: "1-2", labelKey: "calendar.ageBands.1_2" },
  { id: "3-5", labelKey: "calendar.ageBands.3_5" },
  { id: "6-8", labelKey: "calendar.ageBands.6_8" },
  { id: "9-12", labelKey: "calendar.ageBands.9_12" }
];
function isAgeBand(value) {
  return AGE_BANDS.some((band) => band.id === value);
}
function nid(prefix) {
  const raw = typeof crypto !== "undefined" && "randomUUID" in crypto ? crypto.randomUUID().replace(/-/g, "") : Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2);
  return `${prefix}_${raw.slice(0, 12)}`;
}

// src/lib/share/names.ts
function normalizeEmail(email) {
  return email.trim().toLowerCase();
}
function assertEmail(email) {
  const normalized = normalizeEmail(email);
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalized) || normalized.length > 200) {
    throw new ShareError(400, "invalid_email", "Enter a valid email address.");
  }
  return normalized;
}
function canonicalEmail(email) {
  const normalized = normalizeEmail(email);
  const at = normalized.lastIndexOf("@");
  if (at <= 0) return normalized;
  const domain = normalized.slice(at + 1);
  const host = domain === "googlemail.com" ? "gmail.com" : domain;
  if (host !== "gmail.com") return normalized;
  const local = normalized.slice(0, at).split("+")[0]?.replace(/\./g, "") ?? "";
  return `${local}@gmail.com`;
}
function emailIndexKeys(email) {
  const normalized = assertEmail(email);
  const canonical = canonicalEmail(normalized);
  return canonical === normalized ? [normalized] : [normalized, canonical];
}
function actorEmailKeys(actor) {
  const keys = /* @__PURE__ */ new Set();
  for (const raw of [actor.email, ...actor.emails ?? []]) {
    try {
      for (const key of emailIndexKeys(raw)) keys.add(key);
    } catch {
    }
  }
  return [...keys];
}
function emailMatchesActor(inviteEmail, actor) {
  let invite = "";
  try {
    invite = assertEmail(inviteEmail);
  } catch {
    return false;
  }
  const keys = new Set(actorEmailKeys(actor));
  return keys.has(invite) || keys.has(canonicalEmail(invite));
}
function clipDisplayName(raw, fallback) {
  let cleaned = "";
  for (const char of raw) {
    cleaned += char.charCodeAt(0) < 32 ? " " : char;
  }
  cleaned = cleaned.replace(/\s+/g, " ").trim();
  if (!cleaned || cleaned.includes("@")) return fallback.slice(0, 40);
  return cleaned.slice(0, 40);
}
function assertId(id, prefix) {
  if (!new RegExp(`^${prefix}_[a-z0-9_]{8,64}$`).test(id)) {
    throw new ShareError(400, "invalid_id", "Invalid id.");
  }
  return id;
}
function assertDateKey(date) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    throw new ShareError(400, "invalid_date", "Date must look like 2026-09-23.");
  }
  return date;
}
function emailLocalPart(email) {
  return email.split("@")[0]?.replace(/[._+-]+/g, " ").trim() || "Parent";
}

// src/lib/share/mutate.ts
function nowOr(value) {
  return /^\d{4}-\d{2}-\d{2}T/.test(value) ? value : (/* @__PURE__ */ new Date()).toISOString();
}
function sanitizeStep(step, id) {
  const title = step.title.replace(/\s+/g, " ").trim().slice(0, 80);
  if (!title) throw new ShareError(400, "invalid_step", "Each step needs a title.");
  const notes = (step.notes || step.description || "").trim().slice(0, 400);
  const minutes = Math.round(Number(step.minutes));
  if (!Number.isFinite(minutes) || minutes < 1 || minutes > 180) {
    throw new ShareError(400, "invalid_step", "Keep each step between 1 and 180 minutes.");
  }
  const activityId = step.activityId && /^[a-z0-9-]{1,80}$/.test(step.activityId) ? step.activityId : null;
  if (!/^(st|ds)_[a-z0-9_]{8,64}$/.test(id)) {
    throw new ShareError(400, "invalid_id", "Invalid id.");
  }
  return { id, title, notes, description: notes, minutes, activityId };
}
function roleOn(state, childId, actorId) {
  return membershipOnChild(state.memberships, childId, actorId)?.role ?? null;
}
function requireEditor(state, childId, actorId) {
  const role = roleOn(state, childId, actorId);
  if (!canEditPlan(role)) {
    throw new ShareError(403, "forbidden", "You cannot edit this plan.");
  }
  return role;
}
function personOf(state, actorId) {
  return state.people.find((person) => person.id === actorId) ?? null;
}
function applyShareAction(state, actor, action) {
  const now = "now" in action ? nowOr(action.now) : (/* @__PURE__ */ new Date()).toISOString();
  switch (action.type) {
    case "addChild": {
      const person = personOf(state, actor.userId);
      if (!actor.isPro || person?.appRole !== "therapist") {
        throw new ShareError(403, "pro_required", "Only a Pro account can add a patient.");
      }
      if (state.children.length >= 40) {
        throw new ShareError(400, "limit", "This caseload is full.");
      }
      if (!isAgeBand(action.ageBand)) {
        throw new ShareError(400, "invalid_age", "Choose an age band.");
      }
      const childId = assertId(action.childId, "child");
      const child = {
        id: childId,
        displayName: clipDisplayName(action.displayName, "Child"),
        ageBand: action.ageBand,
        createdAt: now,
        createdById: actor.userId
      };
      const allowedTags = new Set(
        state.therapistTags.filter((tag) => tag.therapistId === actor.userId).map((tag) => tag.id)
      );
      return {
        state: {
          ...state,
          children: [...state.children, child],
          memberships: [
            ...state.memberships,
            {
              id: assertId(action.membershipId, "mem"),
              childId,
              personId: actor.userId,
              role: "therapist",
              status: "active"
            }
          ],
          childTags: [
            ...state.childTags,
            ...action.tagIds.filter((tagId) => allowedTags.has(tagId)).map((tagId) => ({ childId, tagId }))
          ],
          selectedChildId: childId
        }
      };
    }
    case "addTherapistTag": {
      const person = personOf(state, actor.userId);
      if (!actor.isPro || person?.appRole !== "therapist") {
        throw new ShareError(403, "pro_required", "Only a Pro account can add tags.");
      }
      const name = clipDisplayName(action.name, "");
      if (!name) return { state };
      return {
        state: {
          ...state,
          therapistTags: [
            ...state.therapistTags,
            { id: assertId(action.tagId, "tag"), therapistId: actor.userId, name }
          ]
        }
      };
    }
    case "setChildTags": {
      const role = roleOn(state, action.childId, actor.userId);
      if (role !== "therapist") {
        throw new ShareError(403, "forbidden", "Only the therapist can tag a patient.");
      }
      const allowed = new Set(
        state.therapistTags.filter((tag) => tag.therapistId === actor.userId).map((tag) => tag.id)
      );
      return {
        state: {
          ...state,
          childTags: [
            ...state.childTags.filter((tag) => tag.childId !== action.childId),
            ...action.tagIds.filter((tagId) => allowed.has(tagId)).map((tagId) => ({ childId: action.childId, tagId }))
          ]
        }
      };
    }
    case "toggleStepDone": {
      if (!roleOn(state, action.childId, actor.userId)) {
        throw new ShareError(403, "forbidden", "You cannot update this plan.");
      }
      assertDateKey(action.date);
      return {
        state: {
          ...state,
          dayPlans: state.dayPlans.map((plan) => {
            if (plan.childId !== action.childId || plan.date !== action.date) return plan;
            return {
              ...plan,
              updatedAt: now,
              steps: plan.steps.map(
                (step) => step.id === action.stepId ? { ...step, done: !step.done } : step
              )
            };
          })
        }
      };
    }
    case "applyLibraryPlan": {
      requireEditor(state, action.childId, actor.userId);
      const plan = state.libraryPlans.find((item) => item.id === action.libraryPlanId);
      if (!plan) throw new ShareError(404, "not_found", "Plan not found.");
      let dayPlans = [...state.dayPlans];
      for (const day of action.days) {
        assertDateKey(day.date);
        if (day.stepIds.length !== plan.steps.length) {
          throw new ShareError(400, "invalid_step", "Step ids do not match the plan.");
        }
        const next = {
          id: assertId(day.dayId, "day"),
          childId: action.childId,
          date: day.date,
          name: plan.name,
          nameKey: plan.nameKey ?? null,
          libraryPlanId: plan.id,
          steps: plan.steps.map((step, index) => ({
            ...sanitizeStep(step, day.stepIds[index]),
            done: false
          })),
          tweaked: false,
          updatedAt: now
        };
        dayPlans = dayPlans.filter(
          (item) => !(item.childId === action.childId && item.date === day.date)
        );
        dayPlans.push(next);
      }
      return { state: { ...state, dayPlans } };
    }
    case "createLibraryPlan": {
      const childId = action.plan.childId;
      if (childId) requireEditor(state, childId, actor.userId);
      else if (!actor.isPro || personOf(state, actor.userId)?.appRole !== "therapist") {
        throw new ShareError(403, "pro_required", "Only a Pro account can add a template.");
      }
      if (state.libraryPlans.length >= 40) {
        throw new ShareError(400, "limit", "Too many plans.");
      }
      const steps = action.plan.steps.slice(0, 30).map((step) => sanitizeStep(step, step.id));
      const plan = {
        id: assertId(action.plan.id, "lib"),
        ownerId: actor.userId,
        name: clipDisplayName(action.plan.name, "Untitled plan"),
        nameKey: action.plan.nameKey ?? null,
        steps,
        childId,
        sourceTemplateId: null,
        updatedAt: now
      };
      return { state: { ...state, libraryPlans: [...state.libraryPlans, plan] } };
    }
    case "updateLibraryPlan": {
      const current = state.libraryPlans.find((plan) => plan.id === action.id);
      if (!current) return { state };
      if (current.childId) requireEditor(state, current.childId, actor.userId);
      else if (current.ownerId !== actor.userId) {
        throw new ShareError(403, "forbidden", "You cannot edit this template.");
      }
      const name = action.name !== void 0 ? clipDisplayName(action.name, current.name) : current.name;
      return {
        state: {
          ...state,
          libraryPlans: state.libraryPlans.map(
            (plan) => plan.id === action.id ? {
              ...plan,
              name,
              nameKey: action.name && action.name !== plan.name ? null : plan.nameKey ?? null,
              steps: action.steps ? action.steps.slice(0, 30).map((step) => sanitizeStep(step, step.id)) : plan.steps,
              updatedAt: now
            } : plan
          )
        }
      };
    }
    case "duplicateLibraryPlan": {
      const source = state.libraryPlans.find((plan) => plan.id === action.sourceId);
      if (!source) return { state };
      if (source.childId) requireEditor(state, source.childId, actor.userId);
      else if (source.ownerId !== actor.userId) {
        throw new ShareError(403, "forbidden", "You cannot copy this template.");
      }
      if (action.stepIds.length !== source.steps.length) {
        throw new ShareError(400, "invalid_step", "Step ids do not match the plan.");
      }
      const copy = {
        ...source,
        id: assertId(action.copyId, "lib"),
        name: clipDisplayName(`${source.name} (copy)`, "Copy"),
        nameKey: null,
        steps: source.steps.map((step, index) => sanitizeStep(step, action.stepIds[index])),
        updatedAt: now
      };
      return { state: { ...state, libraryPlans: [...state.libraryPlans, copy] } };
    }
    case "deleteLibraryPlan": {
      const current = state.libraryPlans.find((plan) => plan.id === action.id);
      if (!current) return { state };
      if (current.childId) requireEditor(state, current.childId, actor.userId);
      else if (current.ownerId !== actor.userId) {
        throw new ShareError(403, "forbidden", "You cannot delete this template.");
      }
      return {
        state: {
          ...state,
          libraryPlans: state.libraryPlans.filter((plan) => plan.id !== action.id)
        }
      };
    }
    case "useTemplateForPatient": {
      if (personOf(state, actor.userId)?.appRole !== "therapist") {
        throw new ShareError(403, "pro_required", "Only a Pro account can copy a template.");
      }
      requireEditor(state, action.childId, actor.userId);
      const master = state.libraryPlans.find(
        (plan) => plan.id === action.masterId && plan.childId === null && plan.ownerId === actor.userId
      );
      if (!master) throw new ShareError(404, "not_found", "Template not found.");
      if (action.stepIds.length !== master.steps.length) {
        throw new ShareError(400, "invalid_step", "Step ids do not match the template.");
      }
      const copy = {
        id: assertId(action.copyId, "lib"),
        ownerId: actor.userId,
        name: master.name,
        nameKey: master.nameKey ?? null,
        steps: master.steps.map((step, index) => sanitizeStep(step, action.stepIds[index])),
        childId: action.childId,
        sourceTemplateId: master.id,
        updatedAt: now
      };
      return { state: { ...state, libraryPlans: [...state.libraryPlans, copy] } };
    }
    case "tweakDayStep": {
      requireEditor(state, action.childId, actor.userId);
      assertDateKey(action.date);
      const title = clipDisplayName(action.title, "");
      if (!title) throw new ShareError(400, "invalid_step", "Each step needs a title.");
      return {
        state: {
          ...state,
          dayPlans: state.dayPlans.map((plan) => {
            if (plan.childId !== action.childId || plan.date !== action.date) return plan;
            return {
              ...plan,
              tweaked: true,
              updatedAt: now,
              steps: plan.steps.map(
                (step) => step.id === action.stepId ? { ...step, title } : step
              )
            };
          })
        }
      };
    }
    case "addDayStep": {
      requireEditor(state, action.childId, actor.userId);
      assertDateKey(action.date);
      const step = { ...sanitizeStep(action.step, action.stepId), done: false };
      const existing = state.dayPlans.find(
        (plan) => plan.childId === action.childId && plan.date === action.date
      );
      if (existing) {
        return {
          state: {
            ...state,
            dayPlans: state.dayPlans.map(
              (plan) => plan.id === existing.id ? { ...plan, steps: [...plan.steps, step], tweaked: true, updatedAt: now } : plan
            )
          }
        };
      }
      return {
        state: {
          ...state,
          dayPlans: [
            ...state.dayPlans,
            {
              id: assertId(action.dayId, "day"),
              childId: action.childId,
              date: action.date,
              name: "Today's plan",
              nameKey: "calendar.today.customPlan",
              libraryPlanId: null,
              steps: [step],
              tweaked: true,
              updatedAt: now
            }
          ]
        }
      };
    }
    case "replaceDayStep": {
      requireEditor(state, action.childId, actor.userId);
      assertDateKey(action.date);
      return {
        state: {
          ...state,
          dayPlans: state.dayPlans.map((plan) => {
            if (plan.childId !== action.childId || plan.date !== action.date) return plan;
            return {
              ...plan,
              tweaked: true,
              updatedAt: now,
              steps: plan.steps.map(
                (step) => step.id === action.stepId ? {
                  ...sanitizeStep({ ...action.step, id: action.stepId }, action.stepId),
                  done: step.done
                } : step
              )
            };
          })
        }
      };
    }
    case "removeDayStep": {
      requireEditor(state, action.childId, actor.userId);
      assertDateKey(action.date);
      return {
        state: {
          ...state,
          dayPlans: state.dayPlans.map((plan) => {
            if (plan.childId !== action.childId || plan.date !== action.date) return plan;
            return {
              ...plan,
              tweaked: true,
              updatedAt: now,
              steps: plan.steps.filter((step) => step.id !== action.stepId)
            };
          })
        }
      };
    }
    case "appendLibraryStep": {
      const plan = state.libraryPlans.find((item) => item.id === action.libraryPlanId);
      if (!plan) return { state };
      if (plan.childId) requireEditor(state, plan.childId, actor.userId);
      else if (plan.ownerId !== actor.userId) {
        throw new ShareError(403, "forbidden", "You cannot edit this template.");
      }
      const step = sanitizeStep(action.step, action.stepId);
      return {
        state: {
          ...state,
          libraryPlans: state.libraryPlans.map(
            (item) => item.id === plan.id ? { ...item, steps: [...item.steps, step].slice(0, 30), updatedAt: now } : item
          )
        }
      };
    }
    case "saveDayBackToLibrary": {
      requireEditor(state, action.childId, actor.userId);
      assertDateKey(action.date);
      const day = state.dayPlans.find(
        (plan) => plan.childId === action.childId && plan.date === action.date
      );
      if (!day) return { state };
      if (action.stepIds.length !== day.steps.length) {
        throw new ShareError(400, "invalid_step", "Step ids do not match the day.");
      }
      const steps = day.steps.map((step, index) => sanitizeStep(step, action.stepIds[index]));
      if (day.libraryPlanId && state.libraryPlans.some((plan) => plan.id === day.libraryPlanId)) {
        return {
          state: {
            ...state,
            libraryPlans: state.libraryPlans.map(
              (plan) => plan.id === day.libraryPlanId ? {
                ...plan,
                name: day.name,
                nameKey: day.nameKey ?? plan.nameKey ?? null,
                steps,
                updatedAt: now
              } : plan
            ),
            dayPlans: state.dayPlans.map(
              (plan) => plan.id === day.id ? { ...plan, tweaked: false } : plan
            )
          }
        };
      }
      const created = {
        id: assertId(action.planId, "lib"),
        ownerId: actor.userId,
        name: day.name,
        nameKey: day.nameKey ?? null,
        steps,
        childId: action.childId,
        sourceTemplateId: null,
        updatedAt: now
      };
      return {
        state: {
          ...state,
          libraryPlans: [...state.libraryPlans, created],
          dayPlans: state.dayPlans.map(
            (plan) => plan.id === day.id ? { ...plan, libraryPlanId: created.id, tweaked: false } : plan
          )
        }
      };
    }
    case "createInvite": {
      const actorRole = roleOn(state, action.childId, actor.userId);
      if (!canInvite(actorRole)) {
        throw new ShareError(403, "forbidden", "You cannot invite someone to this plan.");
      }
      if (!inviteRolesFor(actorRole).includes(action.role)) {
        throw new ShareError(403, "role_not_allowed", "That role is not allowed.");
      }
      const email = assertEmail(action.email);
      const existing = state.invites.find(
        (invite2) => invite2.childId === action.childId && invite2.email === email && invite2.status === "pending"
      );
      const token = assertId(action.token, "tok");
      if (existing) {
        const invite2 = { ...existing, createdAt: now, token, status: "pending" };
        return {
          invite: invite2,
          state: {
            ...state,
            invites: state.invites.map((item) => item.id === existing.id ? invite2 : item)
          }
        };
      }
      if (state.invites.filter((invite2) => invite2.childId === action.childId).length >= 20) {
        throw new ShareError(400, "limit", "Too many invites for this child.");
      }
      const invite = {
        id: assertId(action.inviteId, "inv"),
        childId: action.childId,
        email,
        role: action.role,
        status: "pending",
        invitedById: actor.userId,
        token,
        createdAt: now,
        membershipId: assertId(action.membershipId, "mem"),
        displayName: clipDisplayName(action.displayName, emailLocalPart(email))
      };
      return {
        invite,
        state: {
          ...state,
          memberships: [
            ...state.memberships,
            {
              id: invite.membershipId,
              childId: action.childId,
              personId: assertId(action.pendingPersonId, "pending"),
              role: action.role,
              status: "pending"
            }
          ],
          invites: [...state.invites, invite]
        }
      };
    }
    case "resendInvite": {
      const current = state.invites.find((invite2) => invite2.id === action.inviteId);
      if (!current) throw new ShareError(404, "not_found", "Invite not found.");
      const actorRole = roleOn(state, current.childId, actor.userId);
      if (!canInvite(actorRole)) {
        throw new ShareError(403, "forbidden", "You cannot resend this invite.");
      }
      const invite = {
        ...current,
        createdAt: now,
        token: assertId(action.token, "tok"),
        status: "pending"
      };
      return {
        invite,
        state: {
          ...state,
          invites: state.invites.map((item) => item.id === invite.id ? invite : item)
        }
      };
    }
    case "changeMemberRole": {
      const membership = state.memberships.find((item) => item.id === action.membershipId);
      if (!membership || membership.role === "therapist") {
        throw new ShareError(403, "forbidden", "That role cannot be changed.");
      }
      const actorRole = roleOn(state, membership.childId, actor.userId);
      if (actorRole !== "therapist" && actorRole !== "caregiver") {
        throw new ShareError(403, "forbidden", "You cannot change roles.");
      }
      if (action.role === "therapist") {
        throw new ShareError(403, "forbidden", "You cannot assign the therapist role.");
      }
      return {
        state: {
          ...state,
          memberships: state.memberships.map(
            (item) => item.id === membership.id ? { ...item, role: action.role } : item
          )
        }
      };
    }
    case "removeMember": {
      const membership = state.memberships.find((item) => item.id === action.membershipId);
      if (!membership || membership.role === "therapist") {
        throw new ShareError(403, "forbidden", "The therapist stays on this plan.");
      }
      const actorRole = roleOn(state, membership.childId, actor.userId);
      if (actorRole !== "therapist" && actorRole !== "caregiver") {
        throw new ShareError(403, "forbidden", "You cannot remove this person.");
      }
      return {
        state: {
          ...state,
          memberships: state.memberships.filter((item) => item.id !== membership.id)
        }
      };
    }
    case "removeInvite": {
      const invite = state.invites.find((item) => item.id === action.inviteId);
      if (!invite) return { state };
      const actorRole = roleOn(state, invite.childId, actor.userId);
      if (!canInvite(actorRole)) {
        throw new ShareError(403, "forbidden", "You cannot remove this invite.");
      }
      return {
        state: {
          ...state,
          invites: state.invites.filter((item) => item.id !== invite.id),
          memberships: invite.membershipId ? state.memberships.filter((item) => item.id !== invite.membershipId) : state.memberships
        }
      };
    }
    case "acceptInvite": {
      const invite = state.invites.find((item) => item.token === action.token);
      if (!invite || !emailMatchesActor(invite.email, actor)) {
        throw new ShareError(
          invite ? 403 : 404,
          invite ? "email_mismatch" : "invite_missing",
          invite ? "Sign in with the invited email to accept." : "This invite is missing or already used."
        );
      }
      if (invite.status === "active") return { state };
      const appRole = invite.role === "helper" ? "helper" : "caregiver";
      const person = {
        id: actor.userId,
        name: clipDisplayName(actor.name, invite.displayName),
        email: assertEmail(actor.email),
        appRole
      };
      const people = state.people.some((item) => item.id === person.id) ? state.people.map(
        (item) => item.id === person.id ? {
          ...item,
          name: person.name,
          email: person.email,
          appRole: item.appRole === "therapist" ? "therapist" : appRole
        } : item
      ) : [...state.people, person];
      return {
        invite: { ...invite, status: "active" },
        state: {
          ...state,
          people,
          selectedChildId: invite.childId,
          invites: state.invites.map(
            (item) => item.id === invite.id ? { ...item, status: "active" } : item
          ),
          memberships: state.memberships.map(
            (item) => item.id === invite.membershipId ? { ...item, personId: actor.userId, status: "active", role: invite.role } : item
          )
        }
      };
    }
    default: {
      const unknown = action;
      throw new ShareError(
        400,
        "unknown_action",
        `Unknown action ${unknown.type ?? ""}.`
      );
    }
  }
}

// src/lib/activities-data.ts
var ACTIVITIES = [
  {
    id: "sensory-rice-bin",
    title: "Sensory Rice Bin",
    description: "A calming sensory activity using colored rice to explore textures.",
    minAge: 1,
    maxAge: 3,
    minMinutes: 15,
    maxMinutes: 30,
    skill: "Sensory Play",
    materials: ["Dry rice", "Food colouring", "Shallow bin", "Scoops & cups"],
    steps: [
      "Dye rice with a few drops of food colouring and let it dry.",
      "Pour into a shallow bin and add scoops and small cups.",
      "Sit alongside your child and narrate the textures you feel."
    ]
  },
  {
    id: "tape-rescue",
    title: "Tape Rescue",
    description: "Fine motor activity peeling tape off toys.",
    minAge: 2,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    materials: ["Masking tape", "Favourite small toys"],
    steps: [
      "Tape a few toys down to a table or tray.",
      "Invite your child to free the toys by peeling the tape.",
      "Celebrate each rescue with a high five."
    ]
  },
  {
    id: "mirror-emotions",
    title: "Mirror Emotions",
    description: "Learning to identify and mimic facial expressions.",
    minAge: 3,
    maxAge: 5,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Communication",
    materials: ["A mirror"],
    steps: [
      "Sit together in front of a mirror.",
      "Make a face and name the feeling out loud.",
      "Take turns copying each other's expressions."
    ]
  },
  {
    id: "deep-pressure-sandwich",
    title: "Deep Pressure Sandwich",
    description: "Deep pressure therapy using pillows for regulation.",
    minAge: 2,
    maxAge: 8,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Sensory Play",
    materials: ["Two large cushions"],
    steps: [
      "Ask your child to lie between two cushions.",
      "Press gently and evenly, checking in constantly.",
      "Stop the moment they ask, and count the squeezes together."
    ]
  },
  {
    id: "story-time-props",
    title: "Story Time with Props",
    description: "Using objects to bring a story to life.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 20,
    maxMinutes: 20,
    skill: "Communication",
    materials: ["Picture book", "Matching toys or household items"],
    steps: [
      "Pick a short familiar story.",
      "Hand your child a prop for each character.",
      "Pause and let them fill in the next line."
    ]
  },
  {
    id: "rhyming-match",
    title: "Rhyming Match",
    description: "Phonological awareness development.",
    minAge: 4,
    maxAge: 7,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Communication",
    materials: ["Picture cards or drawings"],
    steps: [
      "Lay out six picture cards in three rhyming pairs.",
      "Say each word slowly and stretch the ending sound.",
      "Let your child pair the ones that sound the same."
    ]
  },
  {
    id: "puppet-conversation",
    title: "Puppet Conversation",
    description: "Encouraging verbal interaction through a proxy.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Communication",
    materials: ["Sock puppet or soft toy"],
    steps: [
      "Introduce the puppet with a silly voice.",
      "Have the puppet ask simple questions.",
      "Let your child answer the puppet, not you."
    ]
  },
  {
    id: "interactive-bubble-chase",
    title: "Interactive Bubble Chase",
    description: "Joint attention and turn-taking fun.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Social Skills",
    materials: ["Bubble mix", "Wand"],
    steps: [
      "Blow a few bubbles and wait for eye contact.",
      "Pause until your child signals for more.",
      "Swap roles and let them try blowing."
    ]
  },
  {
    id: "shadow-puppets",
    title: "Shadow Puppets",
    description: "Exploring light and shadow to build imagination.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Cognitive",
    materials: ["Torch", "Blank wall"],
    steps: [
      "Dim the room and shine a torch at the wall.",
      "Make animal shapes and guess each other's shadow.",
      "Invent a short story with two shadow characters."
    ]
  },
  {
    id: "zip-loc-bag-painting",
    title: "Zip-Loc Bag Painting",
    description: "Mess-free sensory painting.",
    minAge: 1,
    maxAge: 3,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Sensory Play",
    materials: ["Zip-loc bag", "Two paint colours", "Tape"],
    steps: [
      "Squirt paint into the bag and seal it tightly.",
      "Tape the bag to a window or table.",
      "Let your child squish and swirl the colours."
    ]
  },
  {
    id: "color-matching-hunt",
    title: "Color Matching Hunt",
    description: "A whole-house hunt for objects that match a colour card.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Cognitive",
    materials: ["Coloured paper squares", "Basket"],
    steps: [
      "Give your child one colour card at a time.",
      "Hunt the room for objects that match.",
      "Sort the finds into colour piles at the end."
    ]
  },
  {
    id: "calming-glitter-bottle",
    title: "Calming Glitter Bottle",
    description: "A self-regulation tool your child helps build.",
    minAge: 2,
    maxAge: 8,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Self-Care",
    materials: ["Clear bottle", "Warm water", "Glitter glue", "Glitter"],
    steps: [
      "Fill the bottle with warm water and glitter glue.",
      "Add glitter, seal the lid, and shake.",
      "Use it as a timer for calm breathing."
    ]
  },
  {
    id: "obstacle-course",
    title: "Living Room Obstacle Course",
    description: "Gross motor planning with cushions and tunnels.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 20,
    maxMinutes: 30,
    skill: "Motor Skills",
    materials: ["Cushions", "Blanket", "Masking tape"],
    steps: [
      "Build three stations: crawl, jump, balance.",
      "Walk the course together once slowly.",
      "Time each run and cheer the finish."
    ]
  },
  {
    id: "dressing-race",
    title: "Dressing Race",
    description: "Practising independent dressing in a playful way.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Self-Care",
    materials: ["Loose clothes", "Timer"],
    steps: [
      "Lay out one easy garment at a time.",
      "Set a gentle timer and cheer them on.",
      "Finish with a mirror check together."
    ]
  },
  {
    id: "turn-taking-tower",
    title: "Turn-Taking Tower",
    description: "Building a block tower one turn each.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Social Skills",
    materials: ["Wooden blocks"],
    steps: [
      "Say 'my turn' and place a block.",
      "Say 'your turn' and wait patiently.",
      "Knock it down together as the reward."
    ]
  },
  {
    id: "stringing-beads",
    title: "Stringing Beads",
    description: "Threading beads onto a shoelace for fine motor control.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    materials: ["Large beads", "Shoelace or pipe cleaner"],
    steps: [
      "Hold the lace steady for your child.",
      "Show them how to push the bead along.",
      "Make a bracelet or necklace when finished."
    ]
  },
  {
    id: "playdough-pinch",
    title: "Playdough Pinch",
    description: "Strengthen little fingers by pinching and rolling dough.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Playdough", "Cookie cutters"],
    steps: [
      "Roll the dough into small balls.",
      "Pinch each ball between thumb and finger.",
      "Flatten with a cutter and name the shape."
    ]
  },
  {
    id: "clothespin-drop",
    title: "Clothespin Drop",
    description: "Squeezing clothespins to drop pom-poms into a jar.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Clothespins", "Pom-poms", "Jar or cup"],
    steps: [
      "Place pom-poms in a shallow dish.",
      "Use a clothespin to pick up each one.",
      "Drop them into the jar and count together."
    ]
  },
  {
    id: "scooping-and-pouring",
    title: "Scooping and Pouring",
    description: "Transferring water or rice between containers.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    materials: ["Two bowls", "Scoop or cup", "Water or rice"],
    steps: [
      "Fill one bowl with water or rice.",
      "Scoop from the full bowl into the empty one.",
      "Pour slowly and stop when it reaches the top."
    ]
  },
  {
    id: "threading-pasta",
    title: "Threading Pasta",
    description: "Stringing pasta tubes onto a string for hand-eye coordination.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Tube pasta", "Shoelace", "Tape end"],
    steps: [
      "Tape one end of the string to make it stiff.",
      "Show how to push the pasta through.",
      "Hang the finished strand as a decoration."
    ]
  },
  {
    id: "sticker-peel",
    title: "Sticker Peel and Stick",
    description: "Removing and placing stickers for fine motor precision.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Dot stickers", "Paper with drawn shapes"],
    steps: [
      "Peel the edge of each sticker up for your child.",
      "Stick one inside each drawn shape.",
      "Count how many stickers are used."
    ]
  },
  {
    id: "cutting-practice",
    title: "Cutting Practice Strips",
    description: "Safe scissor practice on thick paper strips.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Child-safe scissors", "Thick paper strips", "Tray"],
    steps: [
      "Draw straight lines across the strips.",
      "Hold the paper with one hand and cut with the other.",
      "Drop the snipped pieces into a tray."
    ]
  },
  {
    id: "balance-beam",
    title: "Balance Beam Walk",
    description: "Walking along a low line or tape to practice balance.",
    minAge: 2,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    materials: ["Masking tape", "Floor space"],
    steps: [
      "Make a straight line on the floor with tape.",
      "Walk heel-to-toe along the line.",
      "Add arms out wide or carry a small toy."
    ]
  },
  {
    id: "animal-walks",
    title: "Animal Walks",
    description: "Moving like animals to build core and coordination.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Open floor space"],
    steps: [
      "Bear walk on hands and feet.",
      "Crab walk with tummy up.",
      "Frog jump across the room."
    ]
  },
  {
    id: "bean-bag-toss",
    title: "Bean Bag Toss",
    description: "Aiming and throwing into a target.",
    minAge: 2,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Bean bags or rolled socks", "Box or bucket"],
    steps: [
      "Place the target a few steps away.",
      "Toss underhand and watch where it lands.",
      "Move the target closer or farther."
    ]
  },
  {
    id: "jumping-jacks",
    title: "Jumping Jacks Count",
    description: "Counting while doing jumping jacks for rhythm and body awareness.",
    minAge: 4,
    maxAge: 8,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Motor Skills",
    materials: ["Open space"],
    steps: [
      "Start with arms by your sides.",
      "Jump and spread arms and legs while counting.",
      "Try to reach ten together."
    ]
  },
  {
    id: "simon-says",
    title: "Simon Says Moves",
    description: "Following movement instructions to build listening and control.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Open space"],
    steps: [
      "Say 'Simon says touch your toes'.",
      "Add tricky instructions without the cue.",
      "Switch roles so your child leads."
    ]
  },
  {
    id: "yoga-poses",
    title: "Yoga Poses for Kids",
    description: "Simple poses to stretch and calm the body.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Motor Skills",
    materials: ["Mat or towel", "Open space"],
    steps: [
      "Try tree pose with one foot on the other ankle.",
      "Hold downward dog for a slow count of five.",
      "Finish with child's pose and deep breaths."
    ]
  },
  {
    id: "tweezer-transfer",
    title: "Tweezer Transfer",
    description: "Moving small objects with tweezers for pincer strength.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Tweezers", "Small pompoms", "Muffin tin"],
    steps: [
      "Place one pom-pom in each muffin cup.",
      "Use the tweezers to move them to the other side.",
      "Sort by colour if you have different shades."
    ]
  },
  {
    id: "rolling-tunnel",
    title: "Rolling Crawl Tunnel",
    description: "Crawling through a tunnel made from chairs and a blanket.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Two chairs", "Blanket"],
    steps: [
      "Drape the blanket over the chairs to make a tunnel.",
      "Crawl through from one side to the other.",
      "Place a toy at the end as a reward."
    ]
  },
  {
    id: "hopscotch",
    title: "Hopscotch Grid",
    description: "Hopping and balancing on a numbered grid.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Chalk", "Outdoor space or tape"],
    steps: [
      "Draw a 1\u201310 grid on the ground.",
      "Hop on one foot over single squares.",
      "Land with both feet on the double squares."
    ]
  },
  {
    id: "stacking-cups",
    title: "Stacking Cups",
    description: "Building and nesting cups for hand control.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Plastic cups"],
    steps: [
      "Stack the cups into a tower.",
      "Knock them down carefully.",
      "Nest them back inside each other."
    ]
  },
  {
    id: "hole-punch",
    title: "Hole Punch Fun",
    description: "Punching holes in paper for hand strength.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Single hole punch", "Paper", "Tray"],
    steps: [
      "Draw dots on the paper as targets.",
      "Punch a hole on each dot.",
      "Collect the tiny circles in a tray."
    ]
  },
  {
    id: "target-throwing",
    title: "Target Throwing",
    description: "Throwing soft balls at a target to practice aim.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Soft balls", "Target mat or hula hoop"],
    steps: [
      "Place the target on the floor.",
      "Stand behind a line and throw underhand.",
      "Move the line back after each round."
    ]
  },
  {
    id: "dancing-freeze",
    title: "Dancing Freeze",
    description: "Moving to music and freezing when it stops.",
    minAge: 2,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Music player"],
    steps: [
      "Play music and dance together.",
      "Pause the music suddenly.",
      "Freeze in the silliest pose you can hold."
    ]
  },
  {
    id: "textured-walk",
    title: "Textured Walk",
    description: "Walking barefoot over different surfaces for sensory input.",
    minAge: 1,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Sensory Play",
    materials: ["Towel", "Bubble wrap", "Rug", "Foam mat"],
    steps: [
      "Lay a path of different textures.",
      "Walk slowly and describe each feeling.",
      "Let your child choose the next texture."
    ]
  },
  {
    id: "scented-playdough",
    title: "Scented Playdough",
    description: "Smell and squeeze dough with calming scents.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 15,
    maxMinutes: 20,
    skill: "Sensory Play",
    materials: ["Playdough", "Vanilla or citrus extract"],
    steps: [
      "Add a drop of scent to the dough.",
      "Close your eyes and guess the smell.",
      "Roll and squeeze while breathing slowly."
    ]
  },
  {
    id: "water-pouring",
    title: "Water Pouring Station",
    description: "Pouring water between jugs for calm, focused play.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 15,
    maxMinutes: 20,
    skill: "Sensory Play",
    materials: ["Small jugs", "Water", "Food colouring", "Tray"],
    steps: [
      "Add coloured water to one jug.",
      "Pour carefully into the other.",
      "Stop before it spills and compare levels."
    ]
  },
  {
    id: "sensory-bottle",
    title: "Sensory Bottle",
    description: "Watching objects move slowly in a sealed bottle.",
    minAge: 1,
    maxAge: 6,
    minMinutes: 15,
    maxMinutes: 15,
    skill: "Sensory Play",
    materials: ["Bottle", "Water", "Small beads", "Glitter"],
    steps: [
      "Fill the bottle with water and small items.",
      "Seal the lid tightly with tape.",
      "Tip and shake, then watch everything settle."
    ]
  },
  {
    id: "kinetic-sand",
    title: "Kinetic Sand",
    description: "Squeezing and shaping mouldable sand.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 15,
    maxMinutes: 30,
    skill: "Sensory Play",
    materials: ["Kinetic sand", "Small moulds", "Tray"],
    steps: [
      "Pour sand into a shallow tray.",
      "Press it into moulds and lift slowly.",
      "Squeeze handfuls and let it flow through fingers."
    ]
  },
  {
    id: "noise-shakers",
    title: "Noise Shakers",
    description: "Making shakers and exploring loud and soft sounds.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Sensory Play",
    materials: ["Small jars", "Rice", "Beans", "Beads"],
    steps: [
      "Fill two jars with different fillings.",
      "Shake each and compare the sounds.",
      "Make a loud-soft pattern together."
    ]
  },
  {
    id: "sound-matching",
    title: "Sound Matching",
    description: "Matching pairs of hidden sound containers.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Communication",
    materials: ["Small sealed containers", "Rice", "Beans", "Coins"],
    steps: [
      "Make pairs of identical-sounding containers.",
      "Shake one and listen closely.",
      "Find the container that matches the sound."
    ]
  },
  {
    id: "labeling-hunt",
    title: "Labeling Hunt",
    description: "Finding and naming objects around the room.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Communication",
    materials: ["Picture cards or word labels"],
    steps: [
      "Show a picture card or label.",
      "Search the room for the matching item.",
      "Say the name together when you find it."
    ]
  },
  {
    id: "copycat-words",
    title: "Copycat Words",
    description: "Repeating silly sound chains to build speech imitation.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Communication",
    materials: ["No materials needed"],
    steps: [
      "Say a simple word like 'pop'.",
      "Ask your child to copy you.",
      "Make a chain of three words and take turns."
    ]
  },
  {
    id: "story-sequencing",
    title: "Story Sequencing",
    description: "Ordering picture cards to retell a familiar story.",
    minAge: 4,
    maxAge: 7,
    minMinutes: 15,
    maxMinutes: 20,
    skill: "Communication",
    materials: ["Story picture cards"],
    steps: [
      "Read the story first.",
      "Mix the cards and lay them out.",
      "Put them in order and retell the story."
    ]
  },
  {
    id: "matching-pairs",
    title: "Matching Pairs",
    description: "Memory game turning cards to find matching pictures.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    materials: ["Picture cards"],
    steps: [
      "Shuffle and lay cards face down.",
      "Turn two cards at a time.",
      "Keep the pair if they match."
    ]
  },
  {
    id: "pattern-building",
    title: "Pattern Building",
    description: "Continuing colour or shape patterns with blocks.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    materials: ["Coloured blocks or beads"],
    steps: [
      "Start a simple pattern: red, blue, red, blue.",
      "Ask what comes next.",
      "Let your child make their own pattern."
    ]
  },
  {
    id: "memory-cards",
    title: "Memory Card Game",
    description: "Remembering card positions to find matching pairs.",
    minAge: 4,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    materials: ["Memory card set"],
    steps: [
      "Lay cards face down in a grid.",
      "Turn two cards on each turn.",
      "The player with the most pairs wins."
    ]
  },
  {
    id: "sorting-size",
    title: "Sorting by Size",
    description: "Ordering objects from smallest to largest.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Cognitive",
    materials: ["Three similar objects in different sizes"],
    steps: [
      "Mix the objects together.",
      "Find the smallest and place it first.",
      "Line them up from small to big."
    ]
  },
  {
    id: "pass-the-ball",
    title: "Pass the Ball",
    description: "Rolling a ball back and forth to practise sharing space.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Social Skills",
    materials: ["Soft ball"],
    steps: [
      "Sit facing each other.",
      "Roll the ball and say 'your turn'.",
      "Wait for it to come back before rolling again."
    ]
  },
  {
    id: "greeting-circle",
    title: "Greeting Circle",
    description: "Practising hellos and eye contact in a circle.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Social Skills",
    materials: ["Floor space"],
    steps: [
      "Sit in a circle facing each other.",
      "Wave and say hello to the person next to you.",
      "Add a high five or name greeting."
    ]
  },
  {
    id: "sharing-basket",
    title: "Sharing Basket",
    description: "Taking turns choosing items from a shared basket.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Social Skills",
    materials: ["Basket", "Small toys"],
    steps: [
      "Place a few toys in the basket.",
      "Take turns choosing one.",
      "Say thank you when you receive your turn."
    ]
  },
  {
    id: "button-frame",
    title: "Button Frame",
    description: "Pushing buttons through fabric slots for dressing skills.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Self-Care",
    materials: ["Old shirt or fabric", "Large buttons", "Needle and thread"],
    steps: [
      "Sew buttons onto one side of the fabric.",
      "Cut slots on the other side.",
      "Practice pushing each button through its slot."
    ]
  },
  {
    id: "shoe-lacing",
    title: "Shoe Lacing Practice",
    description: "Threading laces through a practice board or shoe.",
    minAge: 4,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Self-Care",
    materials: ["Shoe or cardboard lacing card", "Shoelace"],
    steps: [
      "Thread the lace up through each hole.",
      "Cross the laces and pull tight.",
      "Make two loops and cross them to tie a bow."
    ]
  },
  {
    id: "setting-table",
    title: "Setting the Table",
    description: "Placing plates and cutlery in the right spots.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Self-Care",
    materials: ["Plate", "Cup", "Fork", "Spoon"],
    steps: [
      "Place the plate in the centre.",
      "Put the fork on the left and spoon on the right.",
      "Add the cup above the plate."
    ]
  },
  {
    id: "hand-washing",
    title: "Hand Washing Steps",
    description: "Following a step-by-step hand washing routine.",
    minAge: 2,
    maxAge: 6,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Self-Care",
    materials: ["Sink", "Soap", "Towel"],
    steps: [
      "Wet hands and add soap.",
      "Rub palms, backs, and between fingers while counting.",
      "Rinse and dry with a towel."
    ]
  },
  {
    id: "finger-paint",
    title: "Finger Paint Patterns",
    description: "Making marks with fingers to explore colour and movement.",
    minAge: 1,
    maxAge: 4,
    minMinutes: 15,
    maxMinutes: 20,
    skill: "Sensory Play",
    materials: ["Washable finger paint", "Paper", "Wipes"],
    steps: [
      "Dip one finger in paint.",
      "Make dots, lines, and circles on paper.",
      "Name the colours and shapes together."
    ]
  },
  {
    id: "brushing-hair",
    title: "Brushing Hair Practice",
    description: "Brushing a doll or their own hair with gentle strokes.",
    minAge: 3,
    maxAge: 6,
    minMinutes: 5,
    maxMinutes: 10,
    skill: "Self-Care",
    materials: ["Hairbrush", "Doll or mirror"],
    steps: [
      "Start at the ends and hold the hair above tangles.",
      "Brush gently from bottom to top.",
      "Look in the mirror and practise a smile."
    ]
  },
  {
    id: "balloon-tap",
    title: "Balloon Tap",
    description: "Keeping a balloon in the air using gentle taps.",
    minAge: 3,
    maxAge: 8,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Motor Skills",
    materials: ["Balloon"],
    steps: [
      "Blow up a balloon and release it gently.",
      "Use hands to tap it up before it lands.",
      "Count how many taps you can make together."
    ]
  },
  {
    id: "face-parts-game",
    title: "Face Parts Game",
    description: "Placing features on a blank face to learn body parts.",
    minAge: 2,
    maxAge: 5,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Communication",
    materials: ["Paper face outline", "Stickers or cut-out features"],
    steps: [
      "Point to each place where eyes, nose, and mouth go.",
      "Stick the features on the face.",
      "Name each part and make the same face."
    ]
  },
  {
    id: "puzzle-time",
    title: "Puzzle Time",
    description: "Completing simple puzzles for problem-solving.",
    minAge: 2,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 20,
    skill: "Cognitive",
    materials: ["Age-appropriate puzzle"],
    steps: [
      "Turn all pieces picture-side up.",
      "Find the corner and edge pieces first.",
      "Match colours and shapes to fill the centre."
    ]
  },
  {
    id: "emotional-cards",
    title: "Emotion Cards",
    description: "Matching feelings words to facial expressions.",
    minAge: 3,
    maxAge: 7,
    minMinutes: 10,
    maxMinutes: 15,
    skill: "Social Skills",
    materials: ["Emotion cards", "Mirror"],
    steps: [
      "Show a card and read the feeling word.",
      "Make that face in the mirror.",
      "Talk about a time you felt that way."
    ]
  }
];

// src/lib/calendar/activity-steps.ts
function planStepFromActivity(activity, keepId) {
  const canonical = ACTIVITIES.find((item) => item.id === activity.id) ?? activity;
  return {
    id: keepId ?? nid("st"),
    title: canonical.title,
    notes: canonical.description,
    description: canonical.description,
    minutes: canonical.minMinutes,
    activityId: canonical.id
  };
}

// src/lib/calendar/seed.ts
function stepsFromCatalog(ids) {
  return ids.map((id) => {
    const activity = ACTIVITIES.find((item) => item.id === id);
    if (!activity) throw new Error(`Seed activity missing from catalog: ${id}`);
    return planStepFromActivity(activity);
  });
}
var THERAPIST_TEMPLATE_ACTIVITIES = {
  "Weekday afternoon calm hour": [
    "calming-glitter-bottle",
    "sensory-rice-bin",
    "deep-pressure-sandwich",
    "story-time-props",
    "yoga-poses"
  ],
  "Morning ready routine": [
    "hand-washing",
    "brushing-hair",
    "dressing-race",
    "shoe-lacing",
    "setting-table"
  ],
  "Sensory and movement break": [
    "animal-walks",
    "obstacle-course",
    "textured-walk",
    "dancing-freeze",
    "balloon-tap"
  ],
  "Homework wind-down": [
    "puzzle-time",
    "story-sequencing",
    "rhyming-match",
    "calming-glitter-bottle",
    "yoga-poses"
  ],
  "Fine motor practice": [
    "stringing-beads",
    "playdough-pinch",
    "clothespin-drop",
    "sticker-peel",
    "cutting-practice"
  ]
};

// src/lib/share/workspace.ts
var TEMPLATE_ROWS = [
  {
    id: "lib_weekday_calm",
    name: "Weekday afternoon calm hour",
    nameKey: "calendar.templates.calmHour"
  },
  { id: "lib_morning_ready", name: "Morning ready routine", nameKey: "calendar.templates.morning" },
  {
    id: "lib_sensory_movement",
    name: "Sensory and movement break",
    nameKey: "calendar.templates.movement"
  },
  {
    id: "lib_homework_winddown",
    name: "Homework wind-down",
    nameKey: "calendar.templates.homework"
  },
  { id: "lib_fine_motor", name: "Fine motor practice", nameKey: "calendar.templates.fineMotor" }
];
function catalogTemplates(ownerId, now) {
  return TEMPLATE_ROWS.map((row) => ({
    id: row.id,
    ownerId,
    name: row.name,
    nameKey: row.nameKey,
    steps: stepsFromCatalog(THERAPIST_TEMPLATE_ACTIVITIES[row.name]),
    childId: null,
    sourceTemplateId: null,
    updatedAt: now
  }));
}
function createOwnerWorkspace(actor, now) {
  const person = {
    id: actor.userId,
    name: clipDisplayName(actor.name, "Therapist"),
    email: actor.email,
    appRole: "therapist"
  };
  return {
    v: 1,
    rev: 1,
    ownerUserId: actor.userId,
    people: [person],
    children: [],
    memberships: [],
    invites: [],
    libraryPlans: catalogTemplates(actor.userId, now),
    dayPlans: [],
    therapistTags: [],
    childTags: []
  };
}
function stateFromWorkspace(ws, activePersonId, selectedChildId = null) {
  return {
    v: 3,
    activePersonId,
    selectedChildId,
    people: ws.people,
    children: ws.children,
    memberships: ws.memberships,
    invites: ws.invites,
    libraryPlans: ws.libraryPlans,
    dayPlans: ws.dayPlans,
    therapistTags: ws.therapistTags,
    childTags: ws.childTags
  };
}
function workspaceFromState(state, ownerUserId, rev) {
  return {
    v: 1,
    rev,
    ownerUserId,
    people: state.people,
    children: state.children,
    memberships: state.memberships,
    invites: state.invites,
    libraryPlans: state.libraryPlans,
    dayPlans: state.dayPlans,
    therapistTags: state.therapistTags,
    childTags: state.childTags
  };
}
function emptyParentState(actor) {
  return blankAccountState({ ...actor, isPro: false });
}
function blankAccountState(actor) {
  const isPro = actor.isPro;
  return {
    v: 3,
    activePersonId: actor.userId,
    selectedChildId: null,
    people: [
      {
        id: actor.userId,
        name: clipDisplayName(actor.name, isPro ? "Therapist" : "Parent"),
        email: actor.email,
        appRole: isPro ? "therapist" : "caregiver"
      }
    ],
    children: [],
    memberships: [],
    invites: [],
    libraryPlans: [],
    dayPlans: [],
    therapistTags: [],
    childTags: []
  };
}
function viewFor(ws, actor) {
  if (ws.ownerUserId === actor.userId) {
    return stateFromWorkspace(ws, actor.userId, null);
  }
  const mine = ws.memberships.filter(
    (membership) => membership.personId === actor.userId && membership.status === "active"
  );
  const childIds = new Set(mine.map((membership) => membership.childId));
  const children = ws.children.filter((child) => childIds.has(child.id));
  const memberships = ws.memberships.filter(
    (membership) => childIds.has(membership.childId) && membership.status === "active"
  );
  const personIds = /* @__PURE__ */ new Set([
    actor.userId,
    ...memberships.map((membership) => membership.personId)
  ]);
  const appRole = mine.some((membership) => membership.role === "caregiver") ? "caregiver" : mine[0]?.role === "helper" ? "helper" : "caregiver";
  const people = ws.people.filter((person) => personIds.has(person.id)).map((person) => person.id === actor.userId ? { ...person, appRole } : person);
  if (!people.some((person) => person.id === actor.userId)) {
    people.push({
      id: actor.userId,
      name: clipDisplayName(actor.name, "Parent"),
      email: actor.email,
      appRole
    });
  }
  return {
    v: 3,
    activePersonId: actor.userId,
    selectedChildId: children.length === 1 ? children[0]?.id ?? null : null,
    people,
    children,
    memberships,
    invites: ws.invites.filter((invite) => childIds.has(invite.childId)),
    libraryPlans: ws.libraryPlans.filter(
      (plan) => plan.childId != null && childIds.has(plan.childId)
    ),
    dayPlans: ws.dayPlans.filter((plan) => childIds.has(plan.childId)),
    therapistTags: [],
    childTags: []
  };
}
function mergeViews(views, actor) {
  if (views.length === 0) return emptyParentState(actor);
  if (views.length === 1) return views[0];
  const base = emptyParentState(actor);
  const people = new Map(base.people.map((person) => [person.id, person]));
  const children = /* @__PURE__ */ new Map();
  const memberships = /* @__PURE__ */ new Map();
  const invites = /* @__PURE__ */ new Map();
  const libraryPlans = /* @__PURE__ */ new Map();
  const dayPlans = /* @__PURE__ */ new Map();
  for (const view of views) {
    for (const person of view.people) people.set(person.id, person);
    for (const child of view.children) children.set(child.id, child);
    for (const membership of view.memberships) memberships.set(membership.id, membership);
    for (const invite of view.invites) invites.set(invite.id, invite);
    for (const plan of view.libraryPlans) libraryPlans.set(plan.id, plan);
    for (const plan of view.dayPlans) dayPlans.set(plan.id, plan);
  }
  const childList = [...children.values()];
  return {
    ...base,
    people: [...people.values()],
    children: childList,
    memberships: [...memberships.values()],
    invites: [...invites.values()],
    libraryPlans: [...libraryPlans.values()],
    dayPlans: [...dayPlans.values()],
    selectedChildId: childList.length === 1 ? childList[0]?.id ?? null : null
  };
}
function mergeInbound(own, inbound) {
  if (inbound.length === 0) return own;
  const people = new Map(own.people.map((person) => [person.id, person]));
  const children = new Map(own.children.map((child) => [child.id, child]));
  const memberships = new Map(own.memberships.map((item) => [item.id, item]));
  const invites = new Map(own.invites.map((item) => [item.id, item]));
  const libraryPlans = new Map(own.libraryPlans.map((item) => [item.id, item]));
  const dayPlans = new Map(own.dayPlans.map((item) => [item.id, item]));
  for (const view of inbound) {
    for (const person of view.people) {
      if (!people.has(person.id)) people.set(person.id, person);
    }
    for (const child of view.children) children.set(child.id, child);
    for (const membership of view.memberships) memberships.set(membership.id, membership);
    for (const invite of view.invites) invites.set(invite.id, invite);
    for (const plan of view.libraryPlans) libraryPlans.set(plan.id, plan);
    for (const plan of view.dayPlans) dayPlans.set(plan.id, plan);
  }
  return {
    ...own,
    people: [...people.values()],
    children: [...children.values()],
    memberships: [...memberships.values()],
    invites: [...invites.values()],
    libraryPlans: [...libraryPlans.values()],
    dayPlans: [...dayPlans.values()]
  };
}
var PLAN_KEEP_DAYS = 60;
function pruneWorkspace(ws, today) {
  const cutoff = new Date(today);
  cutoff.setDate(cutoff.getDate() - PLAN_KEEP_DAYS);
  const cutoffKey = `${cutoff.getFullYear()}-${String(cutoff.getMonth() + 1).padStart(2, "0")}-${String(cutoff.getDate()).padStart(2, "0")}`;
  return {
    ...ws,
    dayPlans: ws.dayPlans.filter((plan) => plan.date >= cutoffKey)
  };
}

// src/lib/share/service.ts
var chains = /* @__PURE__ */ new Map();
function locked(ownerId, fn) {
  const prev = chains.get(ownerId) ?? Promise.resolve();
  const run = prev.then(fn, fn);
  chains.set(
    ownerId,
    run.then(
      () => void 0,
      () => void 0
    )
  );
  return run;
}
function isConflict(err) {
  return Boolean(err && typeof err === "object" && err.code === "conflict");
}
function inviteRedirectUrl(origin, token) {
  let url;
  try {
    url = new URL(origin);
  } catch {
    throw new ShareError(400, "invalid_origin", "Invalid preview address.");
  }
  const host = url.hostname;
  const allowed = host === "localhost" || host === "127.0.0.1" || host === "synlumae.com" || host.endsWith(".vercel.app") || host.endsWith(".github.io");
  if (!allowed) {
    throw new ShareError(400, "invalid_origin", "That address cannot be used for invites.");
  }
  if (url.protocol !== "https:" && host !== "localhost" && host !== "127.0.0.1") {
    throw new ShareError(400, "invalid_origin", "Invite links must use https.");
  }
  return `${url.protocol}//${url.host}/invite/${encodeURIComponent(token)}`;
}
async function ownerIdFor(store, action, actor) {
  switch (action.type) {
    case "addChild":
    case "addTherapistTag":
      if (!actor.isPro)
        throw new ShareError(403, "pro_required", "Only a Pro account can do that.");
      return actor.userId;
    case "createLibraryPlan":
      if (action.plan.childId) {
        const owner = await store.ownerForChild(action.plan.childId);
        if (!owner) throw new ShareError(404, "not_found", "Child not found.");
        return owner;
      }
      if (!actor.isPro)
        throw new ShareError(403, "pro_required", "Only a Pro account can add a template.");
      return actor.userId;
    case "setChildTags":
    case "toggleStepDone":
    case "applyLibraryPlan":
    case "useTemplateForPatient":
    case "tweakDayStep":
    case "addDayStep":
    case "replaceDayStep":
    case "removeDayStep":
    case "saveDayBackToLibrary":
    case "createInvite": {
      const owner = await store.ownerForChild(action.childId);
      if (!owner) throw new ShareError(404, "not_found", "Child not found.");
      return owner;
    }
    case "updateLibraryPlan":
    case "deleteLibraryPlan": {
      const owner = await store.ownerForPlan(action.id);
      if (!owner) throw new ShareError(404, "not_found", "Plan not found.");
      return owner;
    }
    case "duplicateLibraryPlan": {
      const owner = await store.ownerForPlan(action.sourceId);
      if (!owner) throw new ShareError(404, "not_found", "Plan not found.");
      return owner;
    }
    case "appendLibraryStep": {
      const owner = await store.ownerForPlan(action.libraryPlanId);
      if (!owner) throw new ShareError(404, "not_found", "Plan not found.");
      return owner;
    }
    case "resendInvite":
    case "removeInvite": {
      const owner = await store.ownerForInvite(action.inviteId);
      if (!owner) throw new ShareError(404, "not_found", "Invite not found.");
      return owner;
    }
    case "changeMemberRole":
    case "removeMember": {
      const owner = await store.ownerForMembership(action.membershipId);
      if (!owner) throw new ShareError(404, "not_found", "Person not found.");
      return owner;
    }
    case "acceptInvite": {
      const owner = await store.ownerForToken(action.token);
      if (!owner)
        throw new ShareError(404, "invite_missing", "This invite is missing or already used.");
      return owner;
    }
    default:
      throw new ShareError(400, "unknown_action", "Unknown action.");
  }
}
var ShareService = class {
  store;
  mailer;
  constructor(store, mailer) {
    this.store = store;
    this.mailer = mailer;
  }
  async loadOrCreate(actor, ownerId) {
    const existing = await this.store.get(ownerId);
    if (existing) return existing;
    if (ownerId !== actor.userId || !actor.isPro) return null;
    const created = createOwnerWorkspace(actor, (/* @__PURE__ */ new Date()).toISOString());
    await this.store.save(null, created);
    return created;
  }
  async autoAccept(ws, actor) {
    const pending = ws.invites.filter(
      (invite) => invite.status === "pending" && emailMatchesActor(invite.email, actor)
    );
    if (pending.length === 0) return ws;
    return locked(ws.ownerUserId, async () => {
      const fresh = await this.store.get(ws.ownerUserId) ?? ws;
      let state = stateFromWorkspace(fresh, actor.userId);
      let changed = false;
      for (const invite of fresh.invites) {
        if (invite.status !== "pending" || !emailMatchesActor(invite.email, actor)) continue;
        try {
          state = applyShareAction(state, actor, {
            type: "acceptInvite",
            token: invite.token,
            now: (/* @__PURE__ */ new Date()).toISOString()
          }).state;
          changed = true;
        } catch {
        }
      }
      if (!changed) return fresh;
      const next = pruneWorkspace(
        workspaceFromState(state, fresh.ownerUserId, fresh.rev + 1),
        /* @__PURE__ */ new Date()
      );
      await this.store.save(fresh, next);
      return next;
    });
  }
  async snapshot(actor, inviteToken) {
    const owners = new Set(await this.store.ownersForUser(actor.userId));
    for (const emailKey of actorEmailKeys(actor)) {
      for (const ownerId of await this.store.ownersForEmail(emailKey)) owners.add(ownerId);
    }
    if (inviteToken) {
      const ownerId = await this.store.ownerForToken(inviteToken);
      if (ownerId) owners.add(ownerId);
    }
    if (actor.isPro) owners.add(actor.userId);
    let proWorkspace = null;
    const views = [];
    for (const ownerId of owners) {
      const loaded = await this.loadOrCreate(actor, ownerId);
      if (!loaded) continue;
      const ws = await this.autoAccept(loaded, actor);
      if (actor.isPro && ownerId === actor.userId) {
        proWorkspace = ws;
        continue;
      }
      const view = viewFor(ws, actor);
      if (view.children.length > 0) views.push(view);
    }
    if (proWorkspace) {
      const own = viewFor(proWorkspace, actor);
      return { isPro: true, state: mergeInbound(own, views) };
    }
    return { isPro: false, state: mergeViews(views, actor) };
  }
  async peek(token) {
    const ownerId = await this.store.ownerForToken(token);
    if (!ownerId) return null;
    const ws = await this.store.get(ownerId);
    const invite = ws?.invites.find((item) => item.token === token && item.status === "pending");
    if (!ws || !invite) return null;
    const child = ws.children.find((item) => item.id === invite.childId);
    return {
      childDisplayName: child?.displayName ?? "Child",
      role: invite.role,
      email: invite.email
    };
  }
  async act(actor, action, origin) {
    const ownerId = await ownerIdFor(this.store, action, actor);
    const outcome = await locked(ownerId, async () => {
      let email = null;
      let inviteId = null;
      let saved = null;
      for (let attempt = 0; attempt < 3; attempt += 1) {
        const previous = await this.loadOrCreate(actor, ownerId);
        if (!previous) throw new ShareError(404, "not_found", "Shared plan not found.");
        const result = applyShareAction(stateFromWorkspace(previous, actor.userId), actor, action);
        const next = pruneWorkspace(
          workspaceFromState(result.state, ownerId, previous.rev + 1),
          /* @__PURE__ */ new Date()
        );
        try {
          await this.store.save(previous, next);
          saved = next;
          if (result.invite && (action.type === "createInvite" || action.type === "resendInvite")) {
            inviteId = result.invite.id;
            if (result.invite.status === "pending") {
              email = await this.mailer({
                email: result.invite.email,
                token: result.invite.token,
                redirectUrl: inviteRedirectUrl(origin, result.invite.token)
              });
            }
          }
          break;
        } catch (err) {
          if (isConflict(err) && attempt < 2) continue;
          if (isConflict(err)) {
            throw new ShareError(409, "conflict", "Someone else saved. Try again.");
          }
          throw err;
        }
      }
      if (!saved) throw new ShareError(500, "server_error", "Could not save.");
      return { email, inviteId };
    });
    const snap = await this.snapshot(actor);
    return { state: snap.state, email: outcome.email, inviteId: outcome.inviteId };
  }
};

// src/lib/share/store.ts
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
function emptyBag() {
  return {
    workspaces: {},
    child: {},
    plan: {},
    invite: {},
    membership: {},
    token: {},
    user: {},
    email: {}
  };
}
function listAdd(map, key, ownerId) {
  const current = map[key] ?? [];
  if (!current.includes(ownerId)) map[key] = [...current, ownerId];
}
function listRemove(map, key, ownerId) {
  const next = (map[key] ?? []).filter((item) => item !== ownerId);
  if (next.length) map[key] = next;
  else delete map[key];
}
function reindex(bag, previous, next) {
  const ownerId = next.ownerUserId;
  if (previous) {
    for (const child of previous.children) delete bag.child[child.id];
    for (const plan of previous.libraryPlans) delete bag.plan[plan.id];
    for (const invite of previous.invites) {
      delete bag.invite[invite.id];
      delete bag.token[invite.token];
    }
    for (const membership of previous.memberships) delete bag.membership[membership.id];
    for (const membership of previous.memberships) {
      if (membership.status === "active") listRemove(bag.user, membership.personId, ownerId);
    }
    for (const invite of previous.invites) {
      if (invite.status !== "pending") continue;
      for (const emailKey of emailIndexKeys(invite.email)) listRemove(bag.email, emailKey, ownerId);
    }
  }
  bag.workspaces[ownerId] = next;
  for (const child of next.children) bag.child[child.id] = ownerId;
  for (const plan of next.libraryPlans) bag.plan[plan.id] = ownerId;
  for (const invite of next.invites) {
    bag.invite[invite.id] = ownerId;
    if (invite.status === "pending") bag.token[invite.token] = ownerId;
  }
  for (const membership of next.memberships) bag.membership[membership.id] = ownerId;
  const activeUsers = new Set(
    next.memberships.filter((membership) => membership.status === "active").map((membership) => membership.personId)
  );
  activeUsers.add(ownerId);
  for (const userId of activeUsers) listAdd(bag.user, userId, ownerId);
  for (const invite of next.invites) {
    if (invite.status !== "pending") continue;
    for (const emailKey of emailIndexKeys(invite.email)) listAdd(bag.email, emailKey, ownerId);
  }
}
function createMemoryShareStore() {
  const bag = emptyBag();
  return storeFromBag(bag);
}
function storeFromBag(bag) {
  return {
    async get(ownerUserId) {
      return bag.workspaces[ownerUserId] ?? null;
    },
    async save(previous, next) {
      reindex(bag, previous, next);
    },
    async ownerForChild(childId) {
      return bag.child[childId] ?? null;
    },
    async ownerForPlan(planId) {
      return bag.plan[planId] ?? null;
    },
    async ownerForInvite(inviteId) {
      return bag.invite[inviteId] ?? null;
    },
    async ownerForMembership(membershipId) {
      return bag.membership[membershipId] ?? null;
    },
    async ownerForToken(token) {
      return bag.token[token] ?? null;
    },
    async ownersForUser(userId) {
      return [...bag.user[userId] ?? []];
    },
    async ownersForEmail(email) {
      return [...bag.email[email] ?? []];
    }
  };
}
function createFileShareStore(filePath) {
  const bag = emptyBag();
  try {
    const parsed = JSON.parse(readFileSync(filePath, "utf8"));
    Object.assign(bag, parsed);
  } catch {
  }
  const persist = () => {
    mkdirSync(path.dirname(filePath), { recursive: true });
    writeFileSync(filePath, JSON.stringify(bag));
  };
  const inner = storeFromBag(bag);
  return {
    ...inner,
    async save(previous, next) {
      await inner.save(previous, next);
      persist();
    }
  };
}
function readEnv(env, name) {
  return env[name];
}
function redisEnv(env) {
  const url = readEnv(env, "UPSTASH_REDIS_REST_URL") || readEnv(env, "KV_REST_API_URL");
  const token = readEnv(env, "UPSTASH_REDIS_REST_TOKEN") || readEnv(env, "KV_REST_API_TOKEN");
  if (!url || !token) return null;
  return { url: url.replace(/\/$/, ""), token };
}
async function redis(conn, command) {
  const response = await fetch(conn.url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${conn.token}`,
      "content-type": "application/json"
    },
    body: JSON.stringify(command)
  });
  const payload = await response.json();
  if (!response.ok || payload.error) {
    throw new Error(payload.error || `Redis request failed (${response.status}).`);
  }
  return payload.result;
}
var PREFIX = "synlumae:share:";
function createRedisShareStore(conn) {
  const key = (suffix) => `${PREFIX}${suffix}`;
  const readJson2 = async (suffix) => {
    const raw = await redis(conn, ["GET", key(suffix)]);
    if (typeof raw !== "string" || !raw) return null;
    return JSON.parse(raw);
  };
  const writeJson = async (suffix, value) => {
    await redis(conn, ["SET", key(suffix), JSON.stringify(value)]);
  };
  const readList = async (suffix) => {
    return await readJson2(suffix) ?? [];
  };
  const writeList = async (suffix, values) => {
    if (values.length === 0) await redis(conn, ["DEL", key(suffix)]);
    else await writeJson(suffix, values);
  };
  return {
    async get(ownerUserId) {
      return readJson2(`ws:${ownerUserId}`);
    },
    async save(_passed, next) {
      const lock = key(`lock:${next.ownerUserId}`);
      const locked2 = await redis(conn, ["SET", lock, "1", "NX", "EX", "8"]);
      if (locked2 !== "OK") {
        throw Object.assign(new Error("busy"), { code: "conflict" });
      }
      try {
        const previous = await readJson2(`ws:${next.ownerUserId}`);
        if ((previous?.rev ?? 0) !== next.rev - 1) {
          throw Object.assign(new Error("conflict"), { code: "conflict" });
        }
        await writeJson(`ws:${next.ownerUserId}`, next);
        const drop = (suffix) => redis(conn, ["DEL", key(suffix)]);
        if (previous) {
          await Promise.all([
            ...previous.children.map((child) => drop(`child:${child.id}`)),
            ...previous.libraryPlans.map((plan) => drop(`plan:${plan.id}`)),
            ...previous.invites.flatMap((invite) => [
              drop(`invite:${invite.id}`),
              drop(`token:${invite.token}`)
            ]),
            ...previous.memberships.map((membership) => drop(`mem:${membership.id}`))
          ]);
          const prevUsers = new Set(
            previous.memberships.filter((membership) => membership.status === "active").map((membership) => membership.personId)
          );
          for (const userId of prevUsers) {
            const list = (await readList(`user:${userId}`)).filter((id) => id !== next.ownerUserId);
            await writeList(`user:${userId}`, list);
          }
          for (const invite of previous.invites) {
            if (invite.status !== "pending") continue;
            for (const emailKey of emailIndexKeys(invite.email)) {
              const list = (await readList(`email:${emailKey}`)).filter(
                (id) => id !== next.ownerUserId
              );
              await writeList(`email:${emailKey}`, list);
            }
          }
        }
        await Promise.all([
          ...next.children.map(
            (child) => redis(conn, ["SET", key(`child:${child.id}`), next.ownerUserId])
          ),
          ...next.libraryPlans.map(
            (plan) => redis(conn, ["SET", key(`plan:${plan.id}`), next.ownerUserId])
          ),
          ...next.invites.map(
            (invite) => redis(conn, ["SET", key(`invite:${invite.id}`), next.ownerUserId])
          ),
          ...next.invites.filter((invite) => invite.status === "pending").map((invite) => redis(conn, ["SET", key(`token:${invite.token}`), next.ownerUserId])),
          ...next.memberships.map(
            (membership) => redis(conn, ["SET", key(`mem:${membership.id}`), next.ownerUserId])
          )
        ]);
        const users = new Set(
          next.memberships.filter((membership) => membership.status === "active").map((membership) => membership.personId)
        );
        users.add(next.ownerUserId);
        for (const userId of users) {
          const list = await readList(`user:${userId}`);
          if (!list.includes(next.ownerUserId)) {
            await writeList(`user:${userId}`, [...list, next.ownerUserId]);
          }
        }
        for (const invite of next.invites) {
          if (invite.status !== "pending") continue;
          for (const emailKey of emailIndexKeys(invite.email)) {
            const list = await readList(`email:${emailKey}`);
            if (!list.includes(next.ownerUserId)) {
              await writeList(`email:${emailKey}`, [...list, next.ownerUserId]);
            }
          }
        }
      } finally {
        await redis(conn, ["DEL", lock]);
      }
    },
    async ownerForChild(childId) {
      const value = await redis(conn, ["GET", key(`child:${childId}`)]);
      return typeof value === "string" ? value : null;
    },
    async ownerForPlan(planId) {
      const value = await redis(conn, ["GET", key(`plan:${planId}`)]);
      return typeof value === "string" ? value : null;
    },
    async ownerForInvite(inviteId) {
      const value = await redis(conn, ["GET", key(`invite:${inviteId}`)]);
      return typeof value === "string" ? value : null;
    },
    async ownerForMembership(membershipId) {
      const value = await redis(conn, ["GET", key(`mem:${membershipId}`)]);
      return typeof value === "string" ? value : null;
    },
    async ownerForToken(token) {
      const value = await redis(conn, ["GET", key(`token:${token}`)]);
      return typeof value === "string" ? value : null;
    },
    async ownersForUser(userId) {
      return readList(`user:${userId}`);
    },
    async ownersForEmail(email) {
      return readList(`email:${email}`);
    }
  };
}

// src/lib/share/http.ts
import path2 from "node:path";
function readEnv2(env, name) {
  return env[name];
}
function json(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "content-type": "application/json; charset=utf-8" }
  });
}
function errorResponse(err) {
  if (err instanceof ShareError) return json({ error: err.message, code: err.code }, err.status);
  console.error(err);
  return json({ error: "Something went wrong. Try again.", code: "server_error" }, 500);
}
async function readJson(req) {
  if (req.method === "GET" || req.method === "HEAD") return {};
  const text = await req.text();
  if (!text.trim()) return {};
  const parsed = JSON.parse(text);
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new ShareError(400, "invalid_json", "Request body must be an object.");
  }
  return parsed;
}
function match(pathname) {
  const parts = pathname.split("?")[0].replace(/\/+$/, "").split("/").filter(Boolean);
  if (parts[0] !== "api" || parts[1] !== "share") return null;
  const rest = parts.slice(2);
  if (rest.length === 1 && rest[0] === "health") return { name: "health" };
  if (rest.length === 1 && rest[0] === "snapshot") return { name: "snapshot" };
  if (rest.length === 1 && rest[0] === "actions") return { name: "actions" };
  if (rest.length === 2 && rest[0] === "invites")
    return { name: "peek", token: decodeURIComponent(rest[1]) };
  if (rest.length === 3 && rest[0] === "invites" && rest[2] === "accept") {
    return { name: "accept", token: decodeURIComponent(rest[1]) };
  }
  return null;
}
function devActor(req, env) {
  if (readEnv2(env, "SHARE_DEV_BYPASS") !== "1" || readEnv2(env, "VERCEL")) return null;
  const raw = req.headers.get("x-share-dev-user");
  if (!raw) return null;
  const [userId, email, name, pro] = raw.split("|");
  if (!userId || !email || !email.includes("@")) return null;
  return { userId, email, name: name || "Member", isPro: pro === "1" };
}
async function clerkActor(req, secretKey, env) {
  const header2 = req.headers.get("authorization") || "";
  const token = header2.toLowerCase().startsWith("bearer ") ? header2.slice(7).trim() : "";
  if (!token) return null;
  const { verifyToken, createClerkClient } = await import("@clerk/backend");
  const parties = readEnv2(env, "CLERK_AUTHORIZED_PARTIES")?.split(",").map((item) => item.trim()).filter(Boolean);
  const payload = await verifyToken(token, {
    secretKey,
    ...parties && parties.length > 0 ? { authorizedParties: parties } : {}
  });
  const userId = payload.sub;
  if (!userId) return null;
  const user = await createClerkClient({ secretKey }).users.getUser(userId);
  const verified = user.emailAddresses.filter(
    (item) => item.id === user.primaryEmailAddressId || item.verification?.status === "verified"
  ).map((item) => item.emailAddress);
  const external = (user.externalAccounts ?? []).map((item) => item.emailAddress).filter((item) => Boolean(item));
  const emails = [.../* @__PURE__ */ new Set([...verified, ...external])];
  const email = user.emailAddresses.find((item) => item.id === user.primaryEmailAddressId)?.emailAddress ?? emails[0] ?? "";
  if (!email) return null;
  const meta = user.publicMetadata;
  return {
    userId,
    email,
    emails,
    name: user.firstName || user.fullName || email.split("@")[0] || "Member",
    isPro: meta?.isPro === true
  };
}
function createShareDeps(env = process.env) {
  const redis2 = redisEnv(env);
  const secretKey = readEnv2(env, "CLERK_SECRET_KEY");
  const clerk = Boolean(secretKey);
  let store = null;
  let storeName = "none";
  if (redis2) {
    store = createRedisShareStore(redis2);
    storeName = "redis";
  } else if (readEnv2(env, "SHARE_STORE") === "memory") {
    store = createMemoryShareStore();
    storeName = "memory";
  } else if (!readEnv2(env, "VERCEL") && readEnv2(env, "SHARE_STORE") !== "none") {
    const filePath = readEnv2(env, "SHARE_STORE_PATH") || path2.join(process.cwd(), ".data", "share-store.json");
    store = createFileShareStore(filePath);
    storeName = "file";
  }
  const service = store ? new ShareService(
    store,
    (input) => sendClerkInvitation({
      secretKey,
      email: input.email,
      redirectUrl: input.redirectUrl,
      token: input.token
    })
  ) : null;
  return {
    configured: Boolean(service),
    clerk,
    storeName,
    service,
    authenticate: async (req) => {
      const dev = devActor(req, env);
      if (dev) return dev;
      if (!secretKey) return null;
      try {
        return await clerkActor(req, secretKey, env);
      } catch (err) {
        console.error("clerk auth", err);
        return null;
      }
    }
  };
}
var runtime = null;
function shareDeps(env = process.env) {
  const key = [
    readEnv2(env, "UPSTASH_REDIS_REST_URL") || readEnv2(env, "KV_REST_API_URL") || "",
    readEnv2(env, "SHARE_STORE") || "",
    readEnv2(env, "VERCEL") ? "vercel" : "local",
    readEnv2(env, "CLERK_SECRET_KEY") ? "clerk" : "noclerk"
  ].join("|");
  if (runtime?.key === key) return runtime.deps;
  const deps = createShareDeps(env);
  runtime = { key, deps };
  return deps;
}
async function handleShareApi(req, deps) {
  const route = match(new URL(req.url).pathname);
  if (!route) return json({ error: "Not found.", code: "not_found" }, 404);
  if (route.name === "health") {
    return json({
      ok: deps.configured,
      clerk: deps.clerk,
      store: deps.storeName
    });
  }
  if (!deps.service || !deps.configured) {
    return json(
      {
        error: "Live sharing is not configured on this preview yet.",
        code: "not_configured",
        clerk: deps.clerk,
        store: deps.storeName
      },
      503
    );
  }
  try {
    if (route.name === "peek" && req.method === "GET") {
      const preview = await deps.service.peek(route.token);
      if (!preview)
        return json(
          { error: "This invite is missing or already used.", code: "invite_missing" },
          404
        );
      return json(preview);
    }
    const actor = await deps.authenticate(req);
    if (!actor) return json({ error: "Sign in to continue.", code: "unauthorized" }, 401);
    if (route.name === "snapshot" && req.method === "GET") {
      return json(await deps.service.snapshot(actor, req.headers.get("x-share-invite-token")));
    }
    if (route.name === "actions" && req.method === "POST") {
      const body = await readJson(req);
      const action = body["action"];
      const originValue = body["origin"];
      const origin = typeof originValue === "string" ? originValue : "";
      if (!action || typeof action !== "object" || typeof action.type !== "string") {
        throw new ShareError(400, "invalid_action", "Missing action.");
      }
      const result = await deps.service.act(actor, action, origin);
      return json(result);
    }
    if (route.name === "accept" && req.method === "POST") {
      const body = await readJson(req);
      const originValue = body["origin"];
      const origin = typeof originValue === "string" ? originValue : new URL(req.url).origin;
      const result = await deps.service.act(
        actor,
        { type: "acceptInvite", token: route.token, now: (/* @__PURE__ */ new Date()).toISOString() },
        origin
      );
      return json(result);
    }
    return json({ error: "Not found.", code: "not_found" }, 404);
  } catch (err) {
    if (err instanceof SyntaxError) {
      return json({ error: "Request body must be JSON.", code: "invalid_json" }, 400);
    }
    return errorResponse(err);
  }
}

// src/lib/share/node-adapter.ts
function readStream(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (chunk) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));
    req.on("end", () => resolve(Buffer.concat(chunks)));
    req.on("error", reject);
  });
}
function headersFromNode(req) {
  const headers = new Headers();
  for (const [key, value] of Object.entries(req.headers)) {
    if (value === void 0) continue;
    headers.set(key, Array.isArray(value) ? value.join(", ") : value);
  }
  return headers;
}
async function nodeToWebRequest(req) {
  const host = req.headers.host || "localhost";
  const proto = req.headers["x-forwarded-proto"] || "http";
  const url = `${proto}://${host}${req.url || "/"}`;
  const headers = headersFromNode(req);
  const method = req.method || "GET";
  const init = { method, headers };
  if (method !== "GET" && method !== "HEAD") {
    if (req.body !== void 0 && req.body !== null && !Buffer.isBuffer(req.body)) {
      init.body = typeof req.body === "string" ? req.body : JSON.stringify(req.body);
    } else {
      const buf = await readStream(req);
      if (buf.length) init.body = new Uint8Array(buf);
    }
  }
  return new Request(url, init);
}
async function sendWebResponse(res, webRes) {
  res.statusCode = webRes.status;
  webRes.headers.forEach((value, key) => {
    res.setHeader(key, value);
  });
  res.end(Buffer.from(await webRes.arrayBuffer()));
}
function asWebRequest(req) {
  if (!req || typeof req !== "object") return null;
  const row = req;
  if (typeof row.url !== "string" || !/^[a-z][a-z0-9+.-]*:\/\//i.test(row.url)) return null;
  if (typeof row.headers?.get !== "function") return null;
  try {
    return new Request(row.url, row);
  } catch {
    return new Request(row.url, { method: row.method || "GET", headers: row.headers });
  }
}
async function handleShareNode(req, res) {
  const webReq = asWebRequest(req) ?? await nodeToWebRequest(req);
  const webRes = await handleShareApi(webReq, shareDeps());
  if (res && typeof res.end === "function") {
    await sendWebResponse(res, webRes);
    return;
  }
  return webRes;
}

// scripts/share-api-entry.ts
function header(req, name) {
  const value = req.headers[name];
  return Array.isArray(value) ? value[0] : value;
}
function originalUrl(req) {
  const url = req.url || "/";
  if (url.startsWith("/api/share") && !url.includes("share-handler")) return url;
  for (const name of ["x-forwarded-uri", "x-invoke-path", "x-vercel-original-url", "x-url"]) {
    const value = header(req, name);
    if (value && value.includes("/api/share")) return value;
  }
  return url;
}
async function handler(req, res) {
  const headers = req.headers instanceof Headers ? Object.fromEntries(req.headers.entries()) : req.headers;
  const nodeReq = { ...req, headers, url: originalUrl({ url: req.url, headers }) };
  try {
    const result = await handleShareNode(nodeReq, res);
    if (result) return result;
  } catch (err) {
    console.error("share api", err);
    const body = JSON.stringify({ error: "Something went wrong. Try again.", code: "server_error" });
    if (res && typeof res.end === "function") {
      res.statusCode = 500;
      res.setHeader("content-type", "application/json; charset=utf-8");
      res.end(body);
      return;
    }
    return new Response(body, { status: 500, headers: { "content-type": "application/json; charset=utf-8" } });
  }
}
export {
  handler as default
};
