/** Castilian names for country packs. The research JSON only stores English names. */
export const NAME_ES: Record<string, string> = {
  NL: "Países Bajos",
  BE: "Bélgica",
  DE: "Alemania",
  FR: "Francia",
  ES: "España",
  IT: "Italia",
  PT: "Portugal",
  AT: "Austria",
  CH: "Suiza",
  SE: "Suecia",
  NO: "Noruega",
  DK: "Dinamarca",
  FI: "Finlandia",
  PL: "Polonia",
  IE: "Irlanda",
  LU: "Luxemburgo",
  CZ: "Chequia",
  SK: "Eslovaquia",
  HU: "Hungría",
  RO: "Rumanía",
  BG: "Bulgaria",
  GR: "Grecia",
  HR: "Croacia",
  SI: "Eslovenia",
  EE: "Estonia",
  LV: "Letonia",
  LT: "Lituania",
  MT: "Malta",
  CY: "Chipre",
  IS: "Islandia",
  GB: "Reino Unido",
  US: "Estados Unidos",
  CA: "Canadá",
  AR: "Argentina",
  CL: "Chile",
  CO: "Colombia",
  BR: "Brasil",
  PE: "Perú",
};
